'use strict';
(() => {
const G=WB,$=G.$;
const boonLines={};
const bossLines={"guardian":[["This road leads to Yomi. Why have you returned?","I’m looking for a way home."],["The gate is open. Go on.","Thank you. You should rest too."]],"father":[["Ousu, I command you to march east.","I’ve gone far enough. I’m going home."],["You would defy my command?","Yes. I’ll answer for my own choices."]],"aragami":[["Ousu, put down your sword. This mountain has seen enough blood.","I only need a path down."],["You’ve won. Will you take my life too?","Let the people below pass safely, and I’ll sheathe my sword."]],"sea":[["Do you remember the storm at Hashirimizu?","I do. Ototachibana is still in that sea."],["The tide has gone out. Where will you go?","To the shore. To find her."]],"ibuki_heaven":[["One more step, and you’ll die here.","I’ll be careful. Please let me pass."],["You still mean to go on?","Yes. Home is just ahead."]],"prince":[["Do you remember how many people these hands have killed?","I remember. I want to stop."],["Where can we go once we put down the sword?","We could settle in a village. Find some work."]],"whitebird":[["Stay here, and you can forget the pain.","I still remember them. I’m going back."],["There will still be suffering in the world.","I know. Someone is willing to walk with me."]]};
G.dialogue=(speaker,portrait,lines,then)=>{G.hideModal();G.state='dialogue';let step=0;const paint=()=>{const hero=step%2===1,boon=typeof portrait==='number';G.modal(`<div class="dialogue-art ${hero?'speaking':''}"><img src="assets/${G.portrait()}.png" alt="Ousu-no-Mikoto"></div><div class="dialogue-art partner ${hero?'':'speaking'}">${boon?`<div class="boon-portrait" style="background-position:${portrait%4*100/3}% ${Math.floor(portrait/4)*100}%"></div>`:`<img src="assets/${portrait}.png" alt="${speaker}">`}</div><section class="dialogue-lines"><small>${hero?'Ousu-no-Mikoto':speaker}</small><p>${lines[step]}</p><button id="dialogueNext">${step===lines.length-1?'Continue':'Reply'} <kbd>Enter</kbd></button></section>`,'dialogue-modal');$('#dialogueNext').onclick=()=>{step++;if(step>=lines.length){G.hideModal();then();}else paint();};};paint();};
document.addEventListener('keydown',e=>{if(G.state==='dialogue'&&(e.key==='Enter'||e.code==='Space')){e.preventDefault();e.stopImmediatePropagation();$('#dialogueNext')?.click();}},true);
G.bossDialogue=(key,when,then)=>{const b=G.bosses[key];if(!b){then();return;}const pair=(bossLines[key]||bossLines.guardian)[when==='after'?1:0];G.dialogue(b.name,b.art,pair,then);};
G.uiBoss=then=>G.bossDialogue(G.boss.kind,'before',then);
G.offerBlessing=then=>{const boon=()=>{const pool=G.blessings.filter(b=>!G.hasBless(b.id));if(!pool.length){then();return;}G.offer('Hidden Sanctuary','',G.shuffle(pool).slice(0,3).map(b=>({...b,q:b.curse?3:2,tag:b.curse?'Cursed Pact':'Blessing'})),b=>G.dialogue(b.name,G.blessings.findIndex(x=>x.id===b.id),boonLines[b.id],()=>{G.p.blessings.push(b.id);if(b.id==='kushinada'){G.p.maxHp+=24;G.p.hp=Math.min(G.p.maxHp,G.p.hp+24);}if(b.id==='ibuki_curse'){G.p.maxHp=Math.floor(G.p.maxHp*.8);G.p.hp=Math.min(G.p.hp,G.p.maxHp);}if(b.id==='sarutahiko')G.chapterMaps[G.act].revealed=true;G.event('blessing_received',{id:b.id,curse:!!b.curse});G.toast(b.name+' · '+b.text);then();}),'blessing',then);};if(G.currentNode?.type==='boss')G.offer('A Path in the Mirror','',[{id:'divine',name:'Divine · Dawn’s Promise',icon:2,text:'Let divine light guide a human wish.'},{id:'blood',name:'Bloodbound · Uncommanded Blade',icon:0,text:'Carry your scars and choose where your sword will lead.'}],c=>{G.p.pathRank=G.p.path===c.id?Math.min(4,G.p.pathRank+1):1;G.p.path=c.id;G.event('path_upgraded',{path:c.id,rank:G.p.pathRank});boon();},'path_upgrade');else boon();};
})();
