'use strict';
(() => {
const G=WB,$=G.$,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
G.weaponComparison=q=>{if(!G.canTemper())return 'Tempering limit reached for this chapter. Continue next chapter.';q=G.chapterQuality(q);const p=G.p,stats=G.statCompare(G.previewStats(p=>{p.weaponRolls.push(G.temperDelta(q));p.weaponLevel++;p.weaponQuality=Math.max(p.weaponQuality,q);}));return stats+'\n'+[0,1].map(i=>{const a=G.techInfo(i),b=G.techInfo(i,p.weaponLevel+1,p.weapon,Math.max(q,p.weaponQuality));return (i?'R':'F')+' '+a.name+(a.name!==b.name?' → '+b.name:'')+': damage/hit '+a.damage.toFixed(1)+' → '+b.damage.toFixed(1)+'; hits '+a.count+' → '+b.count+'; range '+a.range+' → '+b.range+'; cooldown '+a.cd.toFixed(2)+' → '+b.cd.toFixed(2)+'  s'+(a.stage!==b.stage?'\nNew technique: '+b.text:'');}).join('\n');};
const masteryText={tide_m0:'Each projectile splits into two narrow streams at 32% of its original power.',tide_m1:'Hits pull other enemies within 140 range closer by 7% of their distance per rank.',tide_m2:'R : cast F within 5 s to reduce that F cooldown by 30%.',ember_m0:'Dashing leaves a radius-90 fire field for 2.5 s. It deals 14 × rank base damage every 0.5 s.',ember_m1:'Kills trigger a radius-110 explosion for 14 × rank base damage.',ember_m2:'Hitting Wet enemies releases four steam blades, each with 16 × rank base power. Cooldown: 0.7 s.',wing_m0:'Dashing releases 3 × rank homing feathers, each with 20 base power.',wing_m1:'Damage increases by 10% × rank per 100 distance, up to 45% × rank.',wing_m2:'F  also adds three orbiting feather blades for 3 s.',jade_m0:'Add two orbiting magatama per rank, each with 17 base power. Hit interval: 0.7 s.',jade_m1:'Clear projectiles within 125 range every (5 − rank) seconds.',jade_m2:'F  also releases eight spirit rays, each with 24 × rank base power.',spear_m0:'F  adds three piercing spears, each with 45 × rank base power.',spear_m1:'Each pierced enemy increases subsequent projectile damage by 12% × rank.',spear_m2:'Each hit slows its target for 1.3 s.',hammer_m0:'Lightning branches to up to two other enemies within 200 range, each for 22 base power. Cooldown: 0.4 s.',hammer_m1:'Damage to Wet enemies +25% × rank.',hammer_m2:'F  triggers a radius-140 aftershock after 0.7 s, for 45 × rank base power.',rain_thunder:'Lightning hitting Wet enemies leaps to up to two other enemies within 200 range, each for 22 base power. Cooldown: 0.4 s.',fire_feather:'Feather hits apply Embers for 2 s.',mirror_thunder:'A broken shield deals 25 base lightning damage to up to three enemies.',orbit_dash:'Dashing releases six extra sword waves, each with 18 base power.',frost_vortex:'Vortex hits refresh a 1 s slow.',ember_return:'Returning projectiles become fire-element attacks.',soul_feather:'Q  also releases eight homing feathers, each with 24 base power.',blood_flame:'Killing a burning enemy restores 3 HP. Cooldown: 3 s.'};
for(const t of G.talents){if(masteryText[t.id])t.text=masteryText[t.id];t.text=t.text.replaceAll('Sword Art','F  Technique').replaceAll('Water Art','R  Technique');}const foam=G.talents.find(t=>t.id==='foam_guard');foam.text='R  grants one shield. Trigger cooldown: 18 / 14 / 10 s.';const harvest=G.talents.find(t=>t.id==='harvest');harvest.text='Room-clear healing +2 per rank.';
const offer=G.offer;G.offer=(title,sub,options,then,context,skip)=>{options=options.map(o=>{if(o.id==='reforge'||o.id==='weapon'&&context==='forge')return {...o,icon:G.techInfo(0,G.p.weaponLevel+1).icon,iconSet:'tech',text:o.text.replace('Your weapon and its techniques improve together.','')};if(o.weapon&&o.price){const p=G.p;return {...o,text:o.text+'\n'+[0,1].map(i=>{const a=G.techInfo(i),b=G.techInfo(i,p.weaponLevel,o.weapon,Math.max(p.weaponQuality,o.q));return (i?'R':'F')+' '+a.name+' → '+b.name+': damage/hit '+a.damage.toFixed(1)+' → '+b.damage.toFixed(1)+'; hits '+a.count+' → '+b.count+'; cooldown '+a.cd.toFixed(2)+' → '+b.cd.toFixed(2)+'  s';}).join('\n')};}return o;});offer(title,sub,options,then,context,skip);};
$('#play').insertAdjacentHTML('beforeend','<aside id="itemPopover" role="dialog" aria-label="Item Details" hidden></aside>');
G.closeItemPopover=()=>{const el=$('#itemPopover');if(el.hidden)return;el.hidden=true;if(G.state==='inspect')G.state=G.inspectPrevious||'running';G.keys.clear();};
G.showItemPopover=(type,id,anchor)=>{if(!['running','inspect'].includes(G.state))return;const p=G.p,s=G.combatStats();let name,body,icon,set='items',quality=0;
 if(type==='tech'){const t=G.techInfo(+id);name=t.name;icon=t.icon;set='tech';quality=t.q;body=G.techDescription(t)+'\nAffinity: '+G.affinities[G.weaponProfiles[p.weapon][0]].name+' affinity\nCurrent cooldown: '+(p.skillCooldowns[G.techCooldownKey(+id)]||0).toFixed(2)+'  s\nBase power includes quality and tempering. Hits are further affected by attack bonuses, effect power, critical hits and affinity.';}
 if(type==='weapon'){const w=G.form();name=w.name;icon=G.techInfo(0).icon;set='tech';quality=p.weaponQuality;body=w.text+'\nTempering '+p.weaponLevel+'  rank · '+G.affinities[s.affinity].name+' affinity\nWeapon attack '+s.attack.toFixed(1)+' · Attack speed '+s.attackSpeed.toFixed(2)+'  /s\nCrit chance '+(s.critChance*100).toFixed(1)+'% · Crit damage '+(s.critDamage*100).toFixed(0)+'%\n'+G.runes.find(r=>r.id===p.rune)?.text;}
 if(type==='passive'){const t=G.talents.find(t=>t.id===id);if(!t)return;name=t.name;icon=t.icon;set=t.iconSet||'items';quality=p.talentQualities[id]||0;body=t.text+'\nCurrent '+G.rawLv(id)+' / '+t.max+'  rank · '+G.affinities[G.talentAffinity(t)].name+' affinity\nQuality Resonance (18% total cap): all damage +'+(G.qualities[quality].bonus*6).toFixed(1)+'%';}
 if(type==='relic'){const r=G.relics.find(r=>r.id===id);if(!r)return;name=r.name;icon=r.icon;set=r.iconSet||'items';const rank=p.relicRanks[id]||1;body=G.relicText(r)+'\nInfusion '+rank+' / 3  rank · All damage resonance +'+((rank-1)*4)+'%'+(rank>1&&!r.boss&&!r.mythic?'\nExtra resonance: '+((rank-1)*16)+'  base damage. Cooldown: 1 s.':'');}
 if(type==='blessing'){const b=G.blessings.find(b=>b.id===id);if(!b)return;name=b.name;icon=b.icon;set=b.iconSet||'items';body=b.text;}
 if(type==='q'){name=G.ultimateName();icon=0;set='q';body=G.pathDescription?G.pathDescription(p.path,p.pathRank):p.pathRank<2?'Whitebird sweeps through enemies: 210 base damage and 12 homing feathers with 15 base power each. Clears projectiles and grants 1.2 s of invulnerability.':p.path==='blood'?'Duration: '+(10+p.pathRank*2)+'  s. Attack +55%, attack speed bonus +135%, defense +4, move speed +55, crit chance +12%, crit damage +30%, lifesteal +30%. Lose 2.5% max HP per second. One lethal hit triggers 3 s of death prevention. F / R are sealed during this form.':'Wide-area divine blade: '+(360+p.pathRank*100)+'  base damage. Clears projectiles, grants 1.2 s of invulnerability and 6 s of awakening.';}
 if(!name)return;G.inspectPrevious=G.state==='inspect'?G.inspectPrevious:G.state;G.state='inspect';G.keys.clear();const el=$('#itemPopover');el.innerHTML='<button id="closeItemPopover" aria-label="Close Details">×</button><header>'+G.iconHTML(icon,set)+'<div><small>'+G.qualities[quality].name+'</small><h3>'+esc(name)+'</h3></div></header><p>'+esc(body)+'</p><footer>Esc · Close</footer>';el.hidden=false;const rect=anchor.getBoundingClientRect();el.style.left=Math.max(12,Math.min(innerWidth-el.offsetWidth-12,rect.left))+'px';el.style.top=Math.max(12,Math.min(innerHeight-el.offsetHeight-12,rect.top>innerHeight/2?rect.top-el.offsetHeight-12:rect.bottom+12))+'px';$('#closeItemPopover').onclick=G.closeItemPopover;G.event('item_inspected',{type,id});};
document.addEventListener('click',e=>{const el=e.target.closest('[data-inspect]');if(el){e.preventDefault();e.stopImmediatePropagation();G.showItemPopover(el.dataset.inspect,el.dataset.item,el);}else if(!e.target.closest('#itemPopover'))G.closeItemPopover();},true);
document.addEventListener('keydown',e=>{if(G.state==='inspect'&&e.key==='Escape'){e.stopImmediatePropagation();e.preventDefault();G.closeItemPopover();}},true);
let stamp='';const hud=G.updateHud;G.updateHud=()=>{hud();const p=G.p;if(!p||G.state==='home')return;G.syncWeapon();const s=JSON.stringify([p.weapon,p.weaponLevel,p.weaponQuality,p.passiveSlots,p.talents,p.talentQualities,p.path,p.pathRank,G.inkArtRevision]);if(s!==stamp){stamp=s;const slot=(key,name,icon,set,q,type,id)=>`<button class="loadout-slot" data-inspect="${type}" data-item="${id}" aria-label="Inspect ${esc(name)}" style="--quality:${G.qualities[q||0].color}">${G.iconHTML(icon,set)}<kbd>${key}</kbd><span>${esc(name)}</span></button>`;$('#loadoutBar').innerHTML='<div class="loadout-group"><small>Weapon · '+G.affinities[G.weaponProfiles[p.weapon][0]].name+' affinity</small>'+slot('Auto',G.form().name,G.techInfo(0).icon,'tech',p.weaponQuality,'weapon','')+[0,1].map(i=>{const t=G.techInfo(i);return slot(i?'R':'F',t.name,t.icon,'tech',t.q,'tech',i);}).join('')+slot('Q',G.ultimateName(),0,'q',p.pathRank>=2?4:0,'q','')+'</div><div class="loadout-group passives"><small>Passives</small>'+Array.from({length:6},(_,i)=>{const t=G.talents.find(t=>t.id===p.passiveSlots[i]);return t?slot(G.affinities[G.talentAffinity(t)].name+' '+G.rawLv(t.id),t.name,t.icon,t.iconSet||'items',p.talentQualities[t.id],'passive',t.id):'<div class="loadout-slot empty"><span>Empty</span></div>';}).join('')+'</div>';}
 document.querySelectorAll('[data-inspect="tech"]').forEach(el=>{const cd=p.skillCooldowns[G.techCooldownKey(+el.dataset.item)]||0;el.dataset.cooldown=G.bloodActive()?'Sealed':cd>.05?cd.toFixed(1):'';});const q=$('[data-inspect="q"]');if(q)q.dataset.cooldown=p.power<100?Math.floor(p.power)+'%':'';
 [...$('#buffCrown').children].forEach((el,i)=>{el.dataset.inspect=i<p.equipped.length?'relic':'blessing';el.dataset.item=i<p.equipped.length?p.equipped[i]:p.blessings[i-p.equipped.length];el.setAttribute('role','button');el.onkeydown=e=>{if(e.key==='Enter')G.showItemPopover(el.dataset.inspect,el.dataset.item,el);};});
 const c=G.cinematic,cut=$('#ultimateCutin');if(c&&c.start){const age=(performance.now()-c.start)/1000,alpha=Math.max(0,Math.min(1,age/.14,(.82-age)/.23));cut.style.opacity=alpha;cut.style.transform='translateX('+((1-alpha)*35)+'px)';}else{cut.style.opacity='1';cut.style.transform='none';}
 if(G.interactable?.type==='reward_chest')$('#interactHint').textContent='E · Open Chest';else if(G.exitMarker&&G.distance(p,G.exitMarker)<130){$('#interactHint').hidden=false;$('#interactHint').textContent='E · Depart';}
};
G.dialogue=(speaker,portrait,lines,then)=>{G.closeItemPopover();G.hideModal();G.state='dialogue';G.keys.clear();let step=0;const paint=()=>{const hero=step%2===1,partner=typeof portrait==='number'?G.boonPortraits[portrait]:'assets/'+portrait+'.png';G.modal(`<div class="talk-heading"><span>Encounters in Tokoyo</span><i>Bond</i></div><div class="talk-stage"><figure class="talk-face hero ${hero?'speaking':''}"><img src="assets/${G.portrait()}.png" alt="Ousu-no-Mikoto"><figcaption>Ousu-no-Mikoto</figcaption></figure><div class="talk-seal">✦</div><figure class="talk-face partner ${hero?'':'speaking'}"><img src="${partner}" alt="${esc(speaker)}"><figcaption>${esc(speaker)}</figcaption></figure></div><section class="talk-lines"><small>${hero?'Ousu-no-Mikoto':esc(speaker)}</small><p>${esc(lines[step])}</p><button id="dialogueNext">${step===lines.length-1?'Continue':'Reply'} <kbd>Enter</kbd></button></section>`,'ink-dialogue');$('#dialogueNext').onclick=()=>{if(++step>=lines.length){G.hideModal();then();}else paint();};};paint();};
})();
