'use strict';
(() => {
const G=WB;
G.inkAtlases={};G.techIcons=[];G.boonPortraits=[];G.inkAssetErrors=[];
const load=name=>new Promise(resolve=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>{G.inkAssetErrors.push(name);resolve(null);};im.src='assets/'+name+'.png';});
// Find quiet seams near grid boundaries so generous painted margins survive extraction.
function split(im,cols,rows,adaptive=true){const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const cx=c.getContext('2d',{willReadFrequently:true});cx.drawImage(im,0,0);const data=cx.getImageData(0,0,c.width,c.height).data,out=[],rowEdges=[0];for(let row=1;row<rows;row++){const center=Math.floor(row*im.height/rows),margin=adaptive?Math.floor(im.height/rows*.2):0;let best=center,score=Infinity;for(let yy=center-margin;yy<=center+margin;yy++){let n=Math.abs(yy-center)*.005;for(let xx=0;xx<im.width;xx+=2)n+=data[(yy*im.width+xx)*4+3]>32?1:0;if(n<score){score=n;best=yy;}}rowEdges.push(best);}rowEdges.push(im.height);
 for(let row=0;row<rows;row++){const y=rowEdges[row],h=rowEdges[row+1]-y,edges=[0];for(let col=1;col<cols;col++){const center=Math.floor(col*im.width/cols),margin=adaptive?Math.floor(im.width/cols*.14):0;let best=center,score=Infinity;for(let x=center-margin;x<=center+margin;x++){let n=Math.abs(x-center)*.005;for(let yy=y;yy<y+h;yy+=2)n+=data[(yy*im.width+x)*4+3]>32?1:0;if(n<score){score=n;best=x;}}edges.push(best);}edges.push(im.width);
  for(let col=0;col<cols;col++){const x=edges[col],w=edges[col+1]-x,t=document.createElement('canvas');t.width=w;t.height=h;const tx=t.getContext('2d');tx.drawImage(im,x,y,w,h,0,0,w,h);if(adaptive){const pixels=tx.getImageData(0,0,w,h);for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++){const i=(yy*w+xx)*4+3,edge=Math.min(xx,yy,w-1-xx,h-1-yy);pixels.data[i]*=Math.min(1,edge/7);if(pixels.data[i]<10)pixels.data[i]=0;}tx.putImageData(pixels,0,0);}out.push(t);}
 }return out;}
G.splitInkAtlas=split;
G.inkReady=Promise.all([G.motionReady,...[['a',['kodama','yomotsu','fox']],['b',['soldier','thunder','wraith']],['c',['boar','crab','siren']]].map(async([group,ids])=>{const im=await load('enemies_'+group+'_ink_v7');await G.motionReady;if(im){const frames=split(im,4,6);ids.forEach((id,i)=>G.motion6[id]=frames.slice(i*8,i*8+8));}}),...['tide','ember','wing','jade','spear','thunder','serpent','divinity'].map(async f=>{const im=await load('fx_'+f+'_v7');if(im)G.inkAtlases[f]=split(im,4,2);}),...['ousu_motion_v7','ousu_divine_motion_v7','ousu_blood_motion_v7'].map(async(name,i)=>{const im=await load(name);await G.motionReady;if(im)G.motion6[['hero_motion_v6','hero_divine_motion_v6','hero_blood_motion_v6'][i]]=split(im,4,4);}),load('weapon_icons_v7').then(im=>{if(im)G.techIcons=split(im,6,6,false);}),load('boon_portraits_v7').then(im=>{if(im)G.boonPortraits=split(im,4,2,false).map(c=>c.toDataURL());})]).then(()=>{G.inkLoaded=true;G.inkArtRevision=(G.inkArtRevision||0)+1;});
const family=f=>f==='hammer'?'thunder':f==='divine'?'divinity':f;
function frame(f,row,t){return G.inkAtlases[family(f)]?.[row*4+Math.min(3,Math.max(0,Math.floor(t*4)))];}
function paint(ctx,f,row,t,x,y,a,w,h,alpha=1){const frames=G.inkAtlases[family(f)];if(!frames)return;const phase=Math.min(3,Math.max(0,t*3)),k=Math.floor(phase),mix=phase-k;ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.globalAlpha=alpha*(1-mix);ctx.drawImage(frames[row*4+k],-w/2,-h/2,w,h);if(mix){ctx.globalAlpha=alpha*mix;ctx.drawImage(frames[row*4+Math.min(3,k+1)],-w/2,-h/2,w,h);}ctx.restore();}
G.generatedFx=(index,t)=>frame([G.p?.weapon||'tide','ember','wing','hammer','tide','jade'][index]||'tide',index===5?1:0,t);
G.effect=(x,y,index,size=150,life=.5,rotation=null)=>{const f=[G.p?.weapon||'tide','ember','wing','hammer','tide','jade'][index]||'tide';G.inkEffect(f,x,y,rotation??(index===0?(G.p?.facing||0):0),Math.min(size,420),life,index===5?1:0);};
G.fx3d=(kind,x,y,a=0,strength=1)=>{const f={slash:G.p?.weapon||'tide',bloodSlash:'ember',fire:'ember',thunder:'hammer',wave:'tide',orb:'tide',ripple:'tide',feather:'wing',ultimate:'wing'}[kind]||'jade';G.inkEffect(f,x,y,a,Math.min(330,180*strength),kind==='wave'?.85:.5,['wave','ripple','ultimate'].includes(kind)?1:0,{travel:kind==='wave'?300:0,blood:kind==='bloodSlash'});};
G.bossEffect=(name,x,y,size=300)=>{const f={edict:'divinity',edict6:'divinity',wave:'tide',tide:'tide',sea:'tide',orochi:'serpent',serpent:'serpent',stone:'hammer',quake:'hammer',thunder:'hammer',blood:'ember',prince:'ember',mountain:'hammer',guardian:'hammer',feather:'wing',whitebird:'wing'}[name]||(['sea','magatsu'].includes(G.boss?.kind)?'tide':G.boss?.kind==='ibuki_heaven'?'serpent':G.boss?.kind==='father'?'divinity':'hammer');G.inkEffect(f,x,y,0,Math.min(size,600),.85,['tide','serpent','divinity','wing'].includes(f)?1:0);};
G.drawBossFx=()=>{G.riteFx=[];};
G.drawPaintedFx=ctx=>{G.paintedFx=[];G.inkFx=G.inkFx.filter(f=>G.time-f.start<f.life);for(const f of G.inkFx){const t=(G.time-f.start)/f.life;if(t<0)continue;const alpha=Math.min(1,t/.085,(1-t)/.35)*.88,travel=f.travel||0,x=f.x+Math.cos(f.a)*travel*t,y=f.y+Math.sin(f.a)*travel*t-20,w=f.size*(.85+Math.min(.3,t*.6));let h=w,a=f.a;if(f.family==='tide'&&f.row===1){h=w*.65;}if(f.family==='divine'){h=w*.65;}if(f.family==='wing'&&f.row===1){h=w*.65;}ctx.save();if(f.blood)ctx.filter='saturate(.8) brightness(.7)';paint(ctx,f.family,f.row,t,x,y,a,w,h,alpha);ctx.restore();}
 const p=G.p,o=p?.inkOrbit;if(o){for(let i=0;i<o.count;i++){const a=G.time*3+i*Math.PI*2/o.count;paint(ctx,o.family,0,(G.time*.7+i*.13)%1,p.x+Math.cos(a)*o.r,p.y+Math.sin(a)*o.r*.65-18,a+Math.PI/2,48,48,.9);}}};
G.drawInkZone=(ctx,z)=>{const f=z.inkFamily||({fire:'ember',water:z.vortex?'spear':'tide',thunder:'hammer',bird:'wing'}[z.element]||'jade'),r=z.r;ctx.save();ctx.translate(z.x,z.y);ctx.globalAlpha=z.once?.45:.28;ctx.strokeStyle={ember:'#d27c4d',tide:'#90bbc0',spear:'#779da9',hammer:'#dbbf70',serpent:'#9bbfaf',jade:'#9eaf94'}[f]||'#ede1bc';ctx.lineWidth=z.once?2:3;for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(0,0,r*(.86+i*.045),r*(.86+i*.045),G.time*.25+i*2,.18,Math.PI*1.25);ctx.stroke();}ctx.restore();if(!z.once&&z.age>.1){const size=Math.min(170,r*1.1);for(let i=0;i<3;i++){const a=i*Math.PI*2/3+G.time*.3;paint(ctx,f,1,(z.age*.9+i*.27)%1,z.x+Math.cos(a)*r*.4,z.y+Math.sin(a)*r*.4,0,size,size*.7,.32);}}return true;};
G.drawInkSerpent=(ctx,f,alpha)=>paint(ctx,'serpent',1,1-alpha,f.x,f.y,0,Math.min(f.size,450),Math.min(f.size,450)*.7,alpha*.7);
G.drawEnemyEffectFrame=(ctx,f,t)=>{const name=f.kind==='tide'?'tide':f.kind==='thunder'?'hammer':f.kind==='slash'?'ember':'hammer';paint(ctx,name,f.kind==='tide'||f.kind==='thunder'?1:0,t,f.x,f.y-15,f.kind==='slash'?f.a||0:0,f.kind==='tide'?300:Math.max(120,(f.r||65)*2),f.kind==='tide'?170:Math.max(120,(f.r||65)*2),Math.sin(Math.PI*t)*.85);return true;};
G.drawProjectileFrame=(ctx,s)=>{const f=s.inkFamily||({water:'tide',fire:'ember',bird:'wing',jewel:'jade',thunder:'hammer'}[s.element]||G.p.weapon),w=s.inkSpear?125:s.orb?58:f==='wing'?43:52,h=s.inkSpear?48:s.orb?58:38;paint(ctx,f,0,.33,s.x,s.y,s.a||Math.atan2(s.vy,s.vx),w,h,.95);return true;};
const iconHTML=G.iconHTML,urls=new WeakMap();G.iconHTML=(i,set='items')=>{const c=set==='q'?G.inkAtlases.wing?.[5]:set==='tech'?G.techIcons[i]:G.worldIcons[set]?.[i];if(!c)return iconHTML(i,set==='tech'?'items':set);if(!urls.has(c))urls.set(c,c.toDataURL());return '<span class="item-icon ink-icon" style="background-image:url('+urls.get(c)+')"></span>';};
})();
