'use strict';
(() => {
const G=WB,$=G.$,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
G.journeyReady=Promise.all([G.inkReady,new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{G.worldIcons.myth=G.splitInkAtlas(im,4,3);resolve();};im.onerror=reject;im.src='assets/relic_icons_v8.png';}),new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src='assets/boon_pair_v8.png';}),document.fonts.load('16px "Whitebird Sans"')]).then(([, ,pair])=>{G.boonPortraits.push(...G.splitInkAtlas(pair,2,1,false).map(c=>c.toDataURL()));G.inkArtRevision++;G.journeyLoaded=true;});
G.uiStory=(act,then)=>{const r=G.regions[act];G.offer(r.name,r.intro,[
 {id:'self',name:'Whitebird’s Wish',icon:0,iconSet:'q',tag:'Health & Protection',text:'Max HP +8. Restore 18 HP and gain one shield.',tags:['autonomy','survival']},
 {id:'command',name:'Prince’s Resolve',icon:1,iconSet:'tech',tag:'Attack',text:'Base damage multiplier +5%. Gain 8 coins.',tags:['obedience','damage']}
 ],c=>{if(c.id==='self'){G.autonomy++;G.p.maxHp+=8;G.p.hp=Math.min(G.p.maxHp,G.p.hp+18);G.p.shield++;}else{G.obedience++;G.p.damage+=.05;G.p.gold+=8;}G.event('narrative_choice',{act,choice:c.id});then();},'narrative');};
const boonLines={amaterasu:['There are pursuers ahead. Use my light to see them.','Thank you. I’ll watch my step.'],susanoo:['A storm is coming. Find your footing before you draw.','I want to try holding back this wave.'],kushinada:['Take some rice seeds. You’ll need them when you get home.','I’ll plant them when the roads are safe.'],musashi:['Don’t pull back too soon after a strike. Watch for an opening.','I’ll try again.'],tsukuyomi:['You can walk more slowly tonight. Your wound is still bleeding.','All right. I’ll bind it first.'],ibuki_curse:['Drink this sake. You’ll grow stronger, but wounds will come more easily.','I understand the price.'],sarutahiko:['There’s a village beyond the fork. I’ll show you the way.','I’ll see if anyone needs help.'],yamato:['Do you still have the flint pouch? Keep it safe. You’ll need it.','I do. Aunt, I’ll come back.'],tachibana:['I’m here. When the storm comes, look back for me.','This time, we’ll reach the shore together.'],oousu:['I remember that day. Next time, ask before you strike.','I hurt you. This time, I’ll listen first.']};
G.offerBlessing=then=>{const boon=()=>{const pool=G.blessings.filter(b=>!G.hasBless(b.id));if(!pool.length){then();return;}G.offer('Receive a Blessing','',G.shuffle(pool).slice(0,3).map(b=>({...b,q:b.curse?3:2,tag:b.curse?'Curse':'Blessing'})),b=>G.dialogue(b.name,b.portrait||G.blessings.findIndex(x=>x.id===b.id),boonLines[b.id],()=>{G.p.blessings.push(b.id);if(b.id==='kushinada'){G.p.maxHp+=24;G.p.hp=Math.min(G.p.maxHp,G.p.hp+24);}if(b.id==='ibuki_curse'){G.p.maxHp=Math.floor(G.p.maxHp*.8);G.p.hp=Math.min(G.p.hp,G.p.maxHp);}if(b.id==='sarutahiko')G.chapterMaps[G.act].revealed=true;G.event('blessing_received',{id:b.id,curse:!!b.curse});then();}),'blessing',then);};if(G.currentNode?.type==='boss')G.offer('Choose Your Path','Gain one path rank. Switching paths starts the new path at rank 1.',['divine','blood'].map(id=>{const rank=G.p.path===id?Math.min(4,G.p.pathRank+1):1;return {id,name:id==='divine'?'Whitebird · Divine':'Prince · Bloodbound',icon:id==='divine'?0:1,iconSet:id==='divine'?'q':'tech',tag:`${rank}  Rank`,text:G.pathDescription(id,rank)};}),c=>{G.p.pathRank=G.p.path===c.id?Math.min(4,G.p.pathRank+1):1;G.p.path=c.id;G.event('path_upgraded',{path:c.id,rank:G.p.pathRank});boon();},'path_upgrade');else boon();};
G.passiveValue=id=>{const p=G.p;return (10+(p.talentQualities[id]||0)*5)*(p.talents[id]||0);};
G.sellPassive=id=>{const t=G.talents.find(t=>t.id===id),p=G.p;if(!t||t.mastery||!G.rawLv(id))return false;const gold=G.passiveValue(id),rank=G.rawLv(id);p.passiveSlots=p.passiveSlots.filter(x=>x!==id);delete p.talents[id];delete p.talentQualities[id];if(id==='comb'&&p.equippedCombBonus){p.maxHp-=p.equippedCombBonus;p.equippedCombBonus=0;p.hp=Math.min(p.hp,p.maxHp);}p.gold+=gold;G.event('passive_sold',{id,rank,gold});G.updateHud();return true;};
G.receivePassive=(t,then)=>{if(t.mastery||G.rawLv(t.id)){G.addTalent(t.id,t.q);then();return;}const value=10+(t.q||0)*5;G.offer('New Passive',t.name,[{...t,id:'equip',name:G.p.passiveSlots.length<6?'Equip':'Replace Equipped Passive',text:t.text},{id:'bag',name:'Store in Bag',icon:t.icon,iconSet:t.iconSet,text:'Keep this passive in your bag. Equip it later from the Character screen.'},{id:'sell',name:'Sell',icon:10,iconSet:'voyage',text:`Gain ${value}  coins.`}],c=>{if(c.id==='sell'){G.p.gold+=value;G.event('passive_reward_sold',{id:t.id,quality:t.q,gold:value});then();return;}G.addTalent(t.id,t.q);if(c.id==='bag')G.p.passiveSlots=G.p.passiveSlots.filter(x=>x!==t.id);if(c.id==='equip'&&!G.p.passiveSlots.includes(t.id)){G.manageNewPassive(t.id,then);return;}then();},'passive_disposition');};
document.addEventListener('click',e=>{const el=e.target.closest('[data-sell-passive]');if(!el||G.state!=='character')return;const id=el.dataset.sellPassive,t=G.talents.find(t=>t.id===id),gold=G.passiveValue(id),back=()=>{G.hideModal();G.state='running';G.character();};const after=G.previewStats(p=>{p.passiveSlots=p.passiveSlots.filter(x=>x!==id);delete p.talents[id];delete p.talentQualities[id];});G.offer('Sell Passive',t.name,[{...t,id:'sell',name:`Sell · ${gold} Coins`,text:`Sell all ranks of this passive: ${G.rawLv(id)}  rank(s).\n`+G.statCompare(after)}],()=>{G.sellPassive(id);back();},'passive_sale',back);},true);
G.shop=()=>{const p=G.p,n=G.currentNode;if(!n.stock8){const w=G.pick(G.weapons.filter(w=>w.id!==p.weapon));n.stock8=[{...w,id:'weapon_'+w.id,weapon:w.id,q:G.rollQuality(1),price:38},...G.selectGrowth(G.talentPool()).slice(0,2).map(t=>({...t,id:'talent_'+t.id,talent:t.id,q:G.rollQuality(),price:25})),...G.shuffle(G.relics.filter(r=>!r.boss&&(!G.owned(r.id)||p.relicRanks[r.id]<3))).slice(0,2).map(r=>({...r,id:'relic_'+r.id,relic:r.id,price:28+G.act*3})),{id:'reforge',name:'Tempering Sand',icon:11,q:G.rollQuality(1),price:30},{id:'rice',name:'Warm Rice Ball',icon:9,price:15,text:'Restore 30 HP.'}];}
 G.offer('Lantern Merchant',`Coins ${p.gold}`,n.stock8.filter(c=>!c.sold).map(c=>{let text=c.text||'';if(c.weapon)text+='\n'+G.statCompare(G.previewStats(p=>{p.weapon=c.weapon;p.weaponQuality=Math.max(p.weaponQuality,c.q);}));if(c.id==='reforge')text=G.weaponComparison(c.q);if(c.relic){const r=G.relics.find(r=>r.id===c.relic),rank=p.relicRanks[r.id]||0;text=(rank?`${rank} → ${Math.min(3,rank+1)}  rank(s).\n`:'Takes effect on pickup.\n')+(r.describe?r.describe(Math.min(3,rank+1)):G.relicText(r));}if(c.talent)text+='\nAfter purchase, equip it, store it in your bag or sell it.';return {...c,text:text+`\n${c.price} Coins`,disabled:p.gold<c.price};}),c=>{const item=n.stock8.find(x=>x.id===c.id);if(!item||item.sold||p.gold<item.price)return;p.gold-=item.price;item.sold=true;G.event('shop_purchase',{id:item.id,cost:item.price});if(item.relic)G.gainRelic(item.relic);else if(item.weapon){p.weapon=item.weapon;p.weaponQuality=Math.max(p.weaponQuality,item.q);G.syncWeapon();}else if(item.talent){G.receivePassive({...G.talents.find(t=>t.id===item.talent),q:item.q},G.shop);return;}else if(item.id==='reforge')G.upgradeWeapon(item.q);else p.hp=Math.min(p.maxHp,p.hp+30);G.shop();},'shop',G.completeSupport);
};
const enemyNotes={kodama:'Slow-moving but numerous. Move through gaps to avoid being surrounded.',yomotsu:'A fast pursuer. Dash away before counterattacking.',soldier:'Pursues with a shield, then charges a thrust. Frontal armor reduces damage by 40%; attacking exposes an opening.',fox:'Keeps its distance and fires foxfire, followed by an extra volley.',thunder:'Fires lightning projectiles from afar. Ground circles mark incoming lightning strikes.',wraith:'Splits into separate pursuers as it closes in. Watch for gaps on either side.',boar:'Winds up, then charges in a straight line. Dash sideways to evade.',crab:'Its shell reduces damage by 30%. This protection is lost while attacking or when hit by lightning.',siren:'Fires three water bolts forward. Avoid the point where their paths meet.'};
const enemyLore={kodama:'Inspired by Japanese tales of tree spirits.',yomotsu:'Inspired by the pursuers of Yomi in the Kojiki.',soldier:'A fictional soldier from the eastern campaign.',fox:'Inspired by foxfire folklore.',thunder:'Draws on traditional images of thunder gods and taiko drums.',wraith:'A fictional spirit of those lost at sea.',boar:'Inspired by the white boar of Mount Ibuki.',crab:'A fictional servant of the sea god.',siren:'A fictional tide yokai.'};
G.codexEntries=category=>{
 if(category==='weapons')return G.weapons.map(w=>({...w,iconSet:'tech',icon:G.weaponOrder.indexOf(w.id),detail:`${G.affinities[G.weaponProfiles[w.id][0]].name} affinity · ${G.autoDescriptions[w.id][0]}\n${w.text}\nF: ${G.techniques[w.id][0].map(t=>t[0]).join(' → ')}\nR: ${G.techniques[w.id][1].map(t=>t[0]).join(' → ')}`}));
 if(category==='relics')return G.relics.map(r=>({...r,detail:(r.describe?[1,2,3].map(n=>`${n}  rank: ${r.describe(n)}`).join('\n'):r.text)+'\n'+(r.lore||'A relic inspired by mythological figures and objects.')+'\nIts effects are fictional game mechanics.'}));
 if(category==='enemies')return Object.entries(G.enemyDefs).filter(([id])=>id!=='seal').map(([id,e])=>({id,name:e.name,enemy:id,detail:`${G.affinities[G.affinityFor({kind:id})].name} affinity\nBase HP ${e.hp} · Base move speed ${e.speed}\nStats increase with chapters and elite rooms.\n${enemyNotes[id]||'Watch for attack windups and ground warnings.'}\n${enemyLore[id]||'A fictional enemy created for this game.'}`}));
 return G.blessings.map(b=>({...b,detail:b.text+'\n'+({tachibana:'Ototachibana-hime is Ousu’s wife. In legend, she enters the sea at Hashirimizu to calm its waves. This game imagines their reunion.',oousu:'Oousu-no-Mikoto is Ousu’s elder brother. The Kojiki recounts Ousu killing him. Their reunion and this blessing are fictional adaptations.'}[b.id]||'The blessing’s effects and dialogue were created for this game.')}));
};
G.codex=()=>{if(!['home','running','paused'].includes(G.state))return;const previous=G.state;G.closeItemPopover();G.state='codex';let category='weapons',query='',selected=null;const close=()=>{G.hideModal();G.state=previous;G.keys.clear();if(previous==='paused')G.pause();};
 const render=()=>{const entries=G.codexEntries(category).filter(e=>e.name.toLowerCase().includes(query.toLowerCase())||e.detail.toLowerCase().includes(query.toLowerCase()));const entry=entries.find(e=>e.id===selected)||entries[0];selected=entry?.id;G.modal(`<div class="codex-top"><h2>Journey Codex</h2><button id="codexClose">Close ×</button></div><nav class="tabs">${[['weapons','Weapons'],['relics','Relics'],['enemies','Enemies'],['blessings','Blessing']].map(([id,label])=>`<button data-codex-tab="${id}" class="${category===id?'active':''}">${label}</button>`).join('')}</nav><div class="codex-layout"><aside><input id="codexSearch" placeholder="Search names or effects" value="${esc(query)}" aria-label="Search Codex"><div class="codex-list">${entries.map(e=>`<button data-entry="${e.id}" class="${e.id===selected?'active':''}">${e.enemy?'':G.iconHTML(e.icon,e.iconSet||'items')}<span>${esc(e.name)}</span></button>`).join('')}</div></aside><article class="codex-detail">${entry?`<div class="codex-art">${entry.enemy?`<canvas id="codexEnemy" width="230" height="230"></canvas>`:entry.portrait?`<img src="${typeof entry.portrait==='number'?G.boonPortraits[entry.portrait]:'assets/'+entry.portrait+'.png'}" alt="${esc(entry.name)}">`:G.iconHTML(entry.icon,entry.iconSet||'items')}</div><h3>${esc(entry.name)}</h3><p>${esc(entry.detail)}</p>`:'<p>No matching entries.</p>'}<small>Heaven beats Earth; Earth beats Human; Human beats Heaven. Advantage: ×1.25 damage. Disadvantage: ×0.85.</small></article></div>`,'codex-modal');$('#codexClose').onclick=close;document.querySelectorAll('[data-codex-tab]').forEach(b=>b.onclick=()=>{category=b.dataset.codexTab;selected=null;render();});document.querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>{selected=b.dataset.entry;render();});$('#codexSearch').oninput=e=>{query=e.target.value;const pos=e.target.selectionStart;render();$('#codexSearch').focus();$('#codexSearch').setSelectionRange(pos,pos);};if(entry?.enemy){const c=$('#codexEnemy'),im=G.motion6[entry.enemy]?.[0];if(im)c.getContext('2d').drawImage(im,0,0,230,230);}};G.closeCodex=close;render();G.event('codex_opened',{from:previous});};
$('#loreBtn').onclick=G.codex;$('.hud-actions').insertAdjacentHTML('afterbegin','<button id="codexBtn">Codex <kbd>J</kbd></button>');$('#codexBtn').onclick=G.codex;
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&G.state==='codex'){e.preventDefault();e.stopImmediatePropagation();G.closeCodex();}else if(e.code==='KeyJ'&&['running','home','paused'].includes(G.state)){e.preventDefault();e.stopImmediatePropagation();G.codex();}},true);
const modal=G.modal;G.modal=(...a)=>{modal(...a);if($('#modal').classList.contains('character-modal')&&G.p){const body=$('#tabBody');if(body&&body.textContent.includes('Path: '))body.insertAdjacentHTML('afterbegin','<p>'+esc(G.pathDescription(G.p.path,G.p.pathRank))+'</p>');}};
})();
