'use strict';
(() => {
const G=WB;G.motion6={};G.fx6={};
const load=name=>new Promise(resolve=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>resolve(null);im.src='assets/'+name+'.png';});
function tiles(im,rows){const w=Math.floor(im.width/4),h=Math.floor(im.height/rows);return Array.from({length:rows*4},(_,i)=>{const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,i%4*w,Math.floor(i/4)*h,w,h,0,0,w,h);return c;});}
G.motionReady=Promise.all(['hero_motion_v6','hero_divine_motion_v6','hero_blood_motion_v6','father_motion_v6','enemies_a_motion_v6','enemies_b_motion_v6','enemies_c_motion_v6','fx_combat_v6','fx_spirit_v6'].map(async(name)=>{const im=await load(name);if(!im)return;const frames=tiles(im,name.startsWith('enemies')?6:4);if(name.startsWith('enemies')){const ids=name.includes('_a_')?['kodama','yomotsu','fox']:name.includes('_b_')?['soldier','thunder','wraith']:['boar','crab','siren'];ids.forEach((id,i)=>G.motion6[id]=frames.slice(i*8,i*8+8));}else if(name.startsWith('fx_'))G.fx6[name]=frames;else G.motion6[name]=frames;}));
G.poseFrame=(e,hero,form)=>{let frames,row=0,frame=0;const actor=hero||['prince','whitebird'].includes(e.kind);if(actor){frames=G.motion6[['hero_motion_v6','hero_divine_motion_v6','hero_blood_motion_v6'][form]];}else if(e.kind==='father')frames=G.motion6.father_motion_v6;else frames=G.motion6[e.kind];if(!frames)return null;const action=hero?G.p.action:e.action,moving=hero?(G.moveVector().x||G.moveVector().y):e.walking;if((e.dashTime>0||e.charge>0)&&actor){row=3;frame=Math.min(3,Math.floor((G.time-(action?.start||G.time))/.075));}else if(action?.until>G.time){row=actor?(action.kind==='slash'?1:2):e.kind==='father'?(action.kind==='summon'?3:2):1;frame=Math.min(3,Math.max(0,Math.floor((G.time-action.start)/action.duration*4)));}else if(e.windup>0){row=actor?1:1;frame=e.windup>.3?0:1;}else if(e.animUntil>G.time||e.charge>0){row=1;frame=2;}else if(moving)frame=Math.floor((e.walkTime||G.time)*9)%4;else if(actor){row=1;frame=0;}return frames[row*4+frame]||frames[0];};
G.generatedFx=(index,t)=>{const map={0:['fx_combat_v6',1],1:['fx_spirit_v6',0],2:['fx_spirit_v6',1],3:['fx_combat_v6',2],4:['fx_combat_v6',0],5:['fx_spirit_v6',3]},entry=map[index];return entry&&G.fx6[entry[0]]?.[entry[1]*4+Math.min(3,Math.floor(t*4))];};
const old=G.drawPaintedFx;G.drawPaintedFx=ctx=>{if(!G.fx6.fx_combat_v6){old(ctx);return;}G.paintedFx=G.paintedFx.filter(f=>G.time>=f.start&&G.time-f.start<f.duration);for(const f of G.paintedFx){const t=(G.time-f.start)/f.duration,idx=f.kind==='fire'?1:f.kind==='thunder'?3:['wave','orb','ripple'].includes(f.kind)?4:['feather','ultimate'].includes(f.kind)?2:0,im=f.kind==='bloodSlash'?G.fx6.fx_combat_v6[12+Math.min(3,Math.floor(t*4))]:G.generatedFx(idx,t);if(!im)continue;const size=(f.kind==='ultimate'?420:210)*f.strength;ctx.save();ctx.translate(f.x,f.y-20);if(f.kind==='wave'){ctx.translate(Math.cos(f.a)*(70+t*440),Math.sin(f.a)*(70+t*440));if(Math.cos(f.a)<0)ctx.scale(-1,1);ctx.globalAlpha=Math.sin(Math.PI*Math.min(.97,t+.08))*.9;ctx.drawImage(im,-size*.6,-size*.48,size*1.2,size*.65);}else{ctx.globalAlpha=Math.sin(Math.PI*Math.min(.97,t+.08));ctx.rotate(idx===3?0:f.a);ctx.drawImage(im,-size/2,-size/2,size,size);}ctx.restore();}};
const bossEffect=G.bossEffect;G.bossEffect=(name,...a)=>{if(name!=='edict')bossEffect(name,...a);else G.riteFx.push({name:'edict6',x:a[0],y:a[1],size:a[2]||300,start:G.time,duration:.9});};
const drawBoss=G.drawBossFx;G.drawBossFx=ctx=>{for(const f of G.riteFx){if(f.name!=='edict6')continue;const t=(G.time-f.start)/f.duration,im=G.fx6.fx_spirit_v6?.[8+Math.min(3,Math.floor(t*4))];if(!im||t<0||t>1)continue;ctx.save();ctx.globalAlpha=Math.sin(Math.PI*t)*.85;ctx.drawImage(im,f.x-f.size/2,f.y-f.size*.6,f.size,f.size*.7);ctx.restore();}drawBoss(ctx);};
G.drawEnemyEffectFrame=(ctx,f,t)=>{const idx=f.kind==='tide'?4:f.kind==='thunder'?3:f.kind==='slash'?0:1,im=G.generatedFx(idx,t);if(!im)return false;const size=f.kind==='tide'?360:Math.max(125,(f.r||70)*2);ctx.save();ctx.globalAlpha=Math.sin(Math.PI*t)*.72;ctx.translate(f.x,f.y-25);if(f.kind==='slash')ctx.rotate(f.a||0);ctx.drawImage(im,-size/2,-size/2,size,size);ctx.restore();return true;};
G.drawProjectileFrame=(ctx,s)=>{const idx=s.element==='fire'?1:s.element==='bird'?2:s.element==='thunder'?3:0,im=G.generatedFx(idx,(s.age||0)%1);if(!im)return false;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.a);if(s.element==='water')ctx.filter='hue-rotate(125deg) saturate(1.2)';ctx.globalAlpha=.9;const width=s.orb?68:38,height=s.orb?68:44;ctx.drawImage(im,-width/2,-height/2,width,height);ctx.restore();return true;};
})();
