'use strict';
(() => {
const G=WB,$=G.$,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),qname=q=>G.qualities[q||0].name;
const percent=n=>(n*100).toFixed(1)+'%';
const offer=G.offer;G.offer=(title,subtitle,options,then,context,skip)=>{
 offer(title,subtitle,options,then,context,skip);document.querySelectorAll('[data-choice]').forEach((el,i)=>{const q=options[i].q;if(q!=null){el.style.setProperty('--quality',G.qualities[q].color);el.classList.add('quality-card');el.insertAdjacentHTML('afterbegin',`<span class="quality-label">${qname(q)}</span>`);}});
};
G.offerTalent=(then,context='level_up')=>{
 const show=()=>{const pool=G.talentPool();if(!pool.length){G.p.gold+=12;then();return;}
 const items=G.selectGrowth(pool).map(t=>{const q=G.rollQuality(context==='elite_reward'?1:0);return {...t,q,tag:t.mastery?'Weapon Mastery':'Equippable Passive',text:t.text+` Current ${G.rawLv(t.id)} → ${G.rawLv(t.id)+1}  rank; quality resonance adds all damage ${percent(G.qualities[q].bonus*.12)}.`,effect:{talent:t.id,quality:q}};});
 G.offer('Choose an Upgrade','',items,t=>{G.addTalent(t.id,t.q);if(!t.mastery&&!G.p.passiveSlots.includes(t.id)){G.offer('Passive stored in bag','Passive slots are full. Replace one or store this in your bag.',[{id:'keep',name:'Store in Bag',icon:t.icon,text:t.name},{id:'equip',name:'Manage Now',icon:3,text:'Replace an equipped passive.'}],c=>{if(c.id==='equip')G.manageNewPassive(t.id,then);else then();},'passive_inventory');}else then();},context);
 if(G.p.rerolls>0){$('#modal').insertAdjacentHTML('beforeend',`<button id="qualityReroll" class="secondary">Reroll · ${G.p.rerolls}</button>`);$('#qualityReroll').onclick=()=>{G.p.rerolls--;G.event('growth_rerolled');show();};}
 };show();
};
G.manageNewPassive=(id,then)=>G.offer('Replace Passive','Choose the passive to unequip.',G.p.passiveSlots.map(old=>{const t=G.talents.find(t=>t.id===old);return {...t,text:'Store this in your bag and equip '+G.talents.find(t=>t.id===id).name};}),t=>{G.p.passiveSlots=G.p.passiveSlots.filter(x=>x!==t.id);G.p.passiveSlots.push(id);G.event('passive_swapped',{from:t.id,to:id});then();},'passive_swap',then);
G.receiveSkill=(item,then)=>{const s=G.skillDefs.find(s=>s.id===item.id);G.offer('New Technique',s.name,[
 {id:'f',name:'Equip to F',icon:s.icon,text:'Replace the current F technique. Store the old one in your bag.'},
 {id:'r',name:'Equip to R',icon:s.icon,text:'Replace the current R technique. Store the old one in your bag.'},
 {id:'bag',name:'Store in Bag',icon:3,text:'Keep this technique and equip it later from the Character screen.'},
 {id:'sell',name:'Sell for Coins',icon:3,text:`Sell this technique to gain ${8+item.q*5+item.rank*3}  coins.`}
 ],c=>{if(c.id==='f'||c.id==='r')G.equipSkill(item.uid,c.id==='f'?0:1);else if(c.id==='sell')G.sellSkill(item.uid);then();},'skill_disposition');};
G.offerSkill=then=>G.offer('Technique from an Old Dream','',G.shuffle(G.skillDefs.filter(s=>s.id!=='weapon')).slice(0,3).map(s=>{const q=G.rollQuality(1);return {...s,q,text:s.text+` Power +${Math.round(G.qualities[q].bonus*100)}%.`,effect:{skill:s.id,quality:q}};}),s=>G.receiveSkill(G.acquireSkill(s.id,s.q),then),'skill_reward');
G.offerBlessing=then=>{
 const boon=()=>{const pool=G.blessings.filter(b=>!G.hasBless(b.id));if(!pool.length){then();return;}G.offer('Hidden Sanctuary','Hear the gods of old and echoes of those yet to be born.',G.shuffle(pool).slice(0,3).map(b=>({...b,q:b.curse?3:2,tag:b.curse?'Cursed Pact':'Blessing',effect:{blessing:b.id}})),b=>{
  G.p.blessings.push(b.id);if(b.id==='kushinada'){G.p.maxHp+=24;G.p.hp=Math.min(G.p.maxHp,G.p.hp+24);}if(b.id==='ibuki_curse'){G.p.maxHp=Math.floor(G.p.maxHp*.8);G.p.hp=Math.min(G.p.hp,G.p.maxHp);}if(b.id==='sarutahiko')G.chapterMaps[G.act].revealed=true;G.event('blessing_received',{id:b.id,curse:!!b.curse});then();
 },'blessing',then);};
 if(G.currentNode?.type==='boss')G.offer('Two Homeward Paths','Power may change your form. You still choose where to go.',[{id:'divine',name:'Whitebird · Divine',icon:2,text:'Awaken Ame-no-Murakumo. Q strikes a wide area with the divine blade.',tags:['path','divine']},{id:'blood',name:'Prince · Bloodbound',icon:0,text:'Q Seal your techniques temporarily for rapid melee slashes, lifesteal and one brief reprieve from death.',tags:['path','blood']}],c=>{G.p.pathRank=G.p.path===c.id?Math.min(4,G.p.pathRank+1):1;G.p.path=c.id;G.event('path_upgraded',{path:c.id,rank:G.p.pathRank});boon();},'path_upgrade');else boon();
};
G.forge=()=>{
 const p=G.p,node=G.currentNode;node.forgeQuality??=G.rollQuality();const q=node.forgeQuality,delta=.14+G.qualities[q].bonus*.4,price=20+p.weaponLevel*12;
 const options=[{id:'weapon',name:'Temper',icon:11,q,price,text:`Weapon damage multiplier ${(1+p.weaponRolls.reduce((n,v)=>n+v,0)).toFixed(3)} → ${(1+p.weaponRolls.reduce((n,v)=>n+v,0)+delta).toFixed(3)}; cost: ${price}  coins.`,disabled:p.gold<price,effect:{damage_increment:delta,cost:price,quality:q}},
 {id:'armor',name:'Mend Armor',icon:5,price:25+p.armorLevel*15,text:`Defense +1, max HP +12, restore 20 HP; cost: ${25+p.armorLevel*15}  coins.`,disabled:p.gold<25+p.armorLevel*15},
 ...p.skillBag.filter(s=>s.rank<3).map(s=>{const def=G.skillDefs.find(d=>d.id===s.id),cost=18+s.rank*10;return {id:'skill_'+s.uid,name:def.name,icon:def.icon,q:s.q,price:cost,text:`Technique ${s.rank} → ${s.rank+1}  rank; base power bonus ${Math.round((s.rank-1)*18)}% → ${s.rank*18}%, cooldown multiplier ${(1-(s.rank-1)*.06).toFixed(2)} → ${(1-s.rank*.06).toFixed(2)}; ${cost}  coins.`,disabled:p.gold<cost,skill:s.uid};}),
 ...p.relics.filter(id=>(p.relicRanks[id]||1)<3).map(id=>{const r=G.relics.find(x=>x.id===id),rank=p.relicRanks[id]||1,cost=25+rank*15;return {id:'relic_'+id,name:r.name,icon:r.icon,iconSet:r.iconSet,price:cost,relic:id,disabled:p.gold<cost,text:`Infusion ${rank} → ${rank+1}  rank; all damage resonance +4%. Rank-based trigger effects also improve; ${cost}  coins.`};})];
 G.offer('Flint Forge',`Coins ${p.gold}`,options,c=>{if(p.gold<c.price)return;p.gold-=c.price;
 if(c.id==='weapon'){p.weaponRolls.push(delta);p.weaponLevel++;p.weaponQuality=Math.max(p.weaponQuality,q);}else if(c.id==='armor'){p.armor++;p.armorLevel++;p.maxHp+=12;p.hp=Math.min(p.maxHp,p.hp+20);}else if(c.skill)p.skillBag.find(s=>s.uid===c.skill).rank++;else G.gainRelic(c.relic);
 G.event('equipment_upgraded',{id:c.id,cost:c.price,quality:c.q,weapon_rolls:p.weaponRolls});G.completeSupport();},'forge',G.completeSupport);
};
G.shop=()=>{
 const p=G.p,n=G.currentNode;if(!n.stock)n.stock=[...G.shuffle(G.skillDefs.filter(s=>s.id!=='weapon')).slice(0,2).map(s=>{const q=G.rollQuality(1);return {...s,id:'skill_'+s.id,skill:s.id,q,price:22+q*9};}),...G.selectGrowth(G.talentPool()).slice(0,2).map(t=>{const q=G.rollQuality();return {...t,id:'talent_'+t.id,talent:t.id,q,price:22+q*7};}),{id:'rice',name:'Warm Rice Ball',icon:9,price:15,text:'Restore 30 HP.'}];
 G.offer('Lantern Merchant',`Coins ${p.gold}`,n.stock.filter(s=>!s.sold).map(s=>({...s,text:s.text+` · ${s.price} Coins`,disabled:p.gold<s.price,effect:{cost:s.price,quality:s.q,skill:s.skill,talent:s.talent}})),c=>{
 const item=n.stock.find(s=>s.id===c.id);if(!item||item.sold||p.gold<item.price)return;p.gold-=item.price;item.sold=true;G.event('shop_purchase',{id:item.id,cost:item.price});if(item.skill)G.receiveSkill(G.acquireSkill(item.skill,item.q),G.shop);else{if(item.talent)G.addTalent(item.talent,item.q);else p.hp=Math.min(p.maxHp,p.hp+30);G.shop();}
 },'shop',G.completeSupport);
};
G.uiStory=(act,then)=>{
 const r=G.regions[act];G.offer(r.name,r.intro,[{id:'self',name:'Fight for Those Beside You',icon:2,text:'Restore 10 HP and continue on your own terms.',tags:['autonomy']},{id:'command',name:'Hear the Command, Then Answer',icon:0,text:'Attack +5%. The old voice cannot make your choice.',tags:['obedience']}],c=>{if(c.id==='self'){G.autonomy++;G.p.hp=Math.min(G.p.maxHp,G.p.hp+10);}else{G.obedience++;G.p.damage+=.05;}G.event('narrative_choice',{act,choice:c.id});then();},'narrative');$('#modal').classList.add('story-modal');$('#modal').insertAdjacentHTML('afterbegin',`<img class="story-art" src="assets/${['hero_long','father_portrait','aragami_portrait','sea_portrait','hero_divine_v2'][act]}.png" alt="Chapter artwork">`);
};
G.mapMarkup=()=>{
 const map=G.chapterMaps?.[G.act];if(!map)return '<p>Your journey has not begun.</p>';const nodes=Object.values(map.nodes),minX=Math.min(...nodes.map(n=>n.x)),minY=Math.min(...nodes.map(n=>n.y)),maxX=Math.max(...nodes.map(n=>n.x)),maxY=Math.max(...nodes.map(n=>n.y));
 return `<div class="room-grid" style="grid-template-columns:repeat(${maxX-minX+1},78px);grid-template-rows:repeat(${maxY-minY+1},65px)">${nodes.map(n=>{const visible=map.revealed||n.visited||G.currentNode?.links.some(l=>l.to===n.id);return `<div class="room-cell ${n.id===G.currentNode?.id?'here':''} ${n.cleared?'cleared':''} ${visible?'':'unknown'}" style="grid-column:${n.x-minX+1};grid-row:${n.y-minY+1}">${n.links.map(l=>`<i class="corridor ${l.dir}"></i>`).join('')}<b>${visible?({boss:'Elite',ante:'Heaven',forge:'Forge',shop:'Shop',blessing:'Bless',treasure:'Chest',camp:'Rest',elite:'Spirit',event:'Bond',battle:'Court'}[n.type]):'?'}</b><small>${visible?(G.r2NodeName?.(n)||G.roomNames[n.type]):'Unexplored'}</small></div>`;}).join('')}</div><p class="map-caption">${G.regions[G.act].name} · After clearing a room, leave through any open gate. You can return freely to cleared rooms.</p>`;
};
G.showMap=()=>{if(!['running','paused'].includes(G.state))return;const old=G.state;G.state='map';G.event('map_opened');G.modal(`<h2>Homeward Path</h2>${G.mapMarkup()}<button id="backMap" class="primary">Close Map</button>`,'wide');$('#backMap').onclick=()=>{G.hideModal();G.state='running';if(old==='paused')G.pause();};};$('#mapBtn').onclick=G.showMap;
G.character=()=>{
 if(!['home','running','paused'].includes(G.state))return;const previous=G.state;G.state=previous==='home'?'home':'character';let tab='stats';G.event('character_opened');
 const close=()=>{G.hideModal();G.state=previous;if(previous==='paused')G.pause();};
 const render=()=>{
 const p=G.p&&!G.ended?G.p:null,s=p?G.combatStats():null;
 G.modal(`<div class="character-shell"><aside class="character-art"><img src="assets/${p?G.portrait():'hero_long'}.png" alt="Ousu-no-Mikoto"><div><small>Whitebird Soul</small><h2>Ousu-no-Mikoto</h2><p>${p?.path==='blood'?'Bloodbound · Severance':p?.path==='divine'?'Whitebird · Divine':'Ousu · An Unchosen Path'}</p></div></aside><section class="character-content"><div class="character-top"><div class="eyebrow">Character Journal</div><button id="closeCharacter" class="ghost">Close ×</button></div><nav class="tabs">${[['stats','Stats'],['gear','Weapons'],['skills','Weapon & Techniques'],['passives','Passives'],['relics','Relics'],['bless','Blessing'],['reactions','Reactions']].map(([id,name])=>`<button data-tab="${id}" class="${id===tab?'active':''}">${name}</button>`).join('')}</nav><div id="tabBody"></div></section></div>`,'wide character-modal');
 $('#closeCharacter').onclick=close;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});let html='';
 if(!p)html='<h2>Ousu-no-Mikoto</h2><p>Choose which powers to carry on this journey.</p>';
 else if(tab==='stats'){
 const rows=[['HP',`${Math.ceil(p.hp)} / ${p.maxHp}`],['Weapon Attack',s.attack.toFixed(1)],['Defense',s.armor.toFixed(0)],['Crit Chance',percent(s.critChance)],['Crit Damage',percent(s.critDamage)],['Auto Attack Speed',s.attackSpeed.toFixed(2)+'  /s'],['Global Cooldown Reduction',percent(s.cooldown)],['Effect Power',percent(s.effectPower)],['Lifesteal',percent(s.lifesteal)],['Movement',s.moveSpeed],['Affinity',G.affinities[s.affinity].name],['Coins',p.gold]];
 html=`<h2>Character Stats</h2><div class="stat-grid">${rows.map(([n,v])=>`<div><small>${n}</small><strong>${v}</strong></div>`).join('')}</div><p>Weapon scaling: ${{crit:'Extra crit damage +30%',haste:'Attack speed bonuses also increase damage per hit',effect:'Elemental and triggered damage +25%'}[s.bias]}.</p><p>Heaven beats Earth, Earth beats Human, Human beats Heaven. Advantage ×1.25, disadvantage ×0.85, same affinity ×1. Attack shows the weapon’s base power per hit before technique multipliers, critical hits, elements and affinity.</p><p>F / R Inscriptions, technique rank and talents also affect cooldowns. Select a technique below for details.</p>`;
 }else if(tab==='gear'){
 html=`<h2>${G.form().name}</h2><div class="equipment-main">${G.iconHTML(G.form().icon,'weapons')}<div><h3 style="color:${G.qualities[p.weaponQuality].color}">${qname(p.weaponQuality)} · Tempering ${p.weaponLevel}  Rank</h3><p>${G.form().text}</p></div></div><p>Tempering damage multiplier: ${(1+p.weaponRolls.reduce((n,v)=>n+v,0)).toFixed(3)}×</p><div class="item-list">${p.weaponRolls.map((v,i)=>`<article><b>No. ${i+1}  temper</b><p>Damage multiplier +${v.toFixed(3)}</p></article>`).join('')||'<p>Not yet upgraded.</p>'}</div><h3>Armor</h3><p>Armor rank ${p.armorLevel} , defense ${p.armor}, total defense ${s.armor}.</p><h3>Weapon Mastery</h3>${G.talents.filter(t=>t.weapon===p.weapon&&G.rawLv(t.id)).map(t=>`<p>${t.name} · ${G.rawLv(t.id)}  rank · ${qname(p.talentQualities[t.id])}: ${t.text}</p>`).join('')}`;
 }else if(tab==='skills'){
 html=`<h2>Weapon & Techniques</h2><p>${G.form().name} · Tempering ${p.weaponLevel}  rank · ${G.affinities[G.weaponProfiles[p.weapon][0]].name} affinity</p><div class="bag-list">${p.skillBag.map((item,i)=>{const def=G.skillDefs.find(d=>d.id===item.id);return '<article>'+G.iconHTML(def.icon,def.iconSet||'tech')+'<div><h3>'+((i?'R':'F')+' · '+def.name)+'</h3><p>'+G.techDescription(G.techInfo(i))+'</p><p>'+qname(item.q)+' · Tempering '+p.weaponLevel+'  Rank'+'</p></div></article>';}).join('')}</div>`;
 }else if(tab==='passives'){
 html=`<h2>Passives · ${p.passiveSlots.length} / 6</h2><p>Equip up to six passives. Weapon masteries take effect automatically.</p><div class="bag-list">${G.talents.filter(t=>!t.mastery&&G.rawLv(t.id)).map(t=>`<article style="--quality:${G.qualities[p.talentQualities[t.id]||0].color}">${G.iconHTML(t.icon,t.iconSet||'items')}<div><h3>${t.name} · ${G.affinities[G.talentAffinity(t)].name} affinity · ${G.rawLv(t.id)}  rank <small>${qname(p.talentQualities[t.id])}</small></h3><p>${t.text}</p><p>Quality Resonance (18% total cap): all damage +${percent(G.qualities[p.talentQualities[t.id]||0].bonus*.06)}</p><button data-passive="${t.id}">${p.passiveSlots.includes(t.id)?'Unequip':'Equip'}</button> <button data-sell-passive="${t.id}">Sell · ${G.passiveValue(t.id)} Coins</button></div></article>`).join('')||'<p>Passives found on your journey appear here.</p>'}</div>`;
 }else if(tab==='relics')html=`<h2>Relics · ${p.relics.length}  owned</h2><div class="bag-list">${p.relics.map(id=>{const r=G.relics.find(r=>r.id===id),rank=p.relicRanks[id]||1;return `<article>${G.iconHTML(r.icon,r.iconSet||'items')}<div><h3>${r.name} · ${rank}  Rank</h3><p>${G.relicText(r)}</p><p>Infusion resonance: all damage +${(rank-1)*4}%.${rank>1&&!r.boss&&!r.mythic?'Extra resonance damage '+((rank-1)*16)+'. Triggers at most once per second.':''}</p><small>Effect active while owned</small></div></article>`;}).join('')||'<p>No relics collected yet.</p>'}</div>`;
 else if(tab==='reactions')html=G.r2ComboHTML();
 else if(tab==='bless')html=`<h2>Blessing</h2><p>Path: ${p.path==='blood'?'Bloodstained Prince':p.path==='divine'?'Divine':'Unbound'} · ${p.pathRank}  rank</p><p>${G.pathDescription(p.path,p.pathRank)}</p><div class="item-list">${p.blessings.map(id=>{const b=G.blessings.find(b=>b.id===id);return `<article>${G.iconHTML(b.icon,b.iconSet||'items')}<div><b>${b.name}</b><p>${b.text}</p></div></article>`;}).join('')}</div>`;
 $('#tabBody').innerHTML=html;
 document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{G.equipSkill(b.dataset.equip,+b.dataset.slot);render();});document.querySelectorAll('[data-sell]').forEach(b=>b.onclick=()=>{G.sellSkill(b.dataset.sell);render();});
 document.querySelectorAll('[data-passive]').forEach(b=>b.onclick=()=>{const id=b.dataset.passive;if(p.passiveSlots.includes(id))p.passiveSlots=p.passiveSlots.filter(x=>x!==id);else if(p.passiveSlots.length<6)p.passiveSlots.push(id);else{G.notice('Unequip a passive first.');return;}G.event('passive_equipped',{id,active:p.passiveSlots.includes(id)});render();});document.querySelectorAll('[data-relic]').forEach(b=>b.onclick=()=>{G.equipRelic(b.dataset.relic);render();});
 };render();
};$('#characterHome').onclick=G.character;$('#characterBtn').onclick=G.character;
$('#play').insertAdjacentHTML('beforeend','<div id="buffCrown" aria-label="Owned Relics and Blessings"></div><div id="miniMap"></div><div id="ultimateCutin" hidden><img alt="Awakening portrait"><div><small>True Name Unleashed</small><h2></h2><p></p></div></div>');
const hud=G.updateHud;let mapStamp='',buffStamp='';G.updateHud=()=>{
 hud();const p=G.p;if(!p||G.state==='home')return;
 $('#blackSkill').hidden=true;$('#weaponName').textContent=G.form().name;$('#roomName').textContent=G.roomNames[G.currentNode?.type]||'Homeward Path';$('#roomClock').textContent=G.roomDone?'Gate Open':G.roomType==='boss'?'Spirits Remain':['battle','elite'].includes(G.roomType)?'Defeat the Enemies':'A Lantern Still Burns';
 for(let i=0;i<2;i++){const item=G.skillInfo(i),def=G.skillDefs.find(d=>d.id===item?.id),cd=p.skillCooldowns[item?.id]||0;$(i?'#waterText':'#skillText').textContent=G.bloodActive()?'Sealed':cd>0?cd.toFixed(1)+'s':def?.name||'Empty';}
 $('#awakeText').textContent=G.bloodActive()?`Severance ${(p.bloodUntil-G.time).toFixed(1)}s`:p.power>=100?(p.path==='blood'?'Severance · Ready':'Divine Blade · Ready'):Math.floor(p.power)+'%';
 const stamp=JSON.stringify([p.equipped,p.relicRanks,p.blessings]);if(stamp!==buffStamp){buffStamp=stamp;$('#buffCrown').innerHTML=p.equipped.map(id=>{const r=G.relics.find(r=>r.id===id);return `<span tabindex="0" title="${esc(r.name+': '+G.relicText(r))}">${G.iconHTML(r.icon,r.iconSet||'items')}<b>${p.relicRanks[id]||1}</b></span>`;}).join('')+p.blessings.map(id=>{const b=G.blessings.find(b=>b.id===id);return `<span tabindex="0" class="blessing-buff" title="${esc(b.name+': '+b.text)}">${G.iconHTML(b.icon)}</span>`;}).join('');}
 $('#relicStrip').innerHTML='';
 const ms=JSON.stringify([G.act,G.currentNode?.id,G.currentNode?.cleared,Object.values(G.chapterMaps[G.act]?.nodes||{}).filter(n=>n.visited).length,G.chapterMaps[G.act]?.revealed]);if(ms!==mapStamp){mapStamp=ms;$('#miniMap').innerHTML=G.mapMarkup();}
 if(G.interactable){$('#interactHint').hidden=false;$('#interactHint').textContent='E · '+({departure:'Depart',blessing:'Receive Blessing',treasure:'Open Chest',forge:'Temper',shop:'Trade',camp:'Rest',event:'Talk'}[G.interactable.type]||'Interact');}
 const c=G.cinematic,el=$('#ultimateCutin');if(c&&performance.now()<c.until){el.hidden=false;el.querySelector('img').src='assets/'+c.art+'.png';el.querySelector('h2').textContent=c.name;el.querySelector('p').textContent=c.line;}else{el.hidden=true;G.cinematic=null;}
};
const update=G.update;G.update=dt=>{if(G.cinematic&&performance.now()<G.cinematic.until)return;update(dt);};
const result=G.uiResult;G.uiResult=()=>{
 result();const bossCount=document.querySelectorAll('.result-stats b')[1];if(bossCount)bossCount.textContent=G.summary().bosses_defeated+' / '+(G.regions.length+1);if(G.session.status!=='victory')return;
 const blood=G.p.path==='blood',heading=document.querySelector('.result-layout h2'),story=document.querySelector('.result-layout section > p');
 if(heading)heading.textContent=blood?'I’m going home.':'I’m back.';
 if(story)story.textContent=blood?'The whitebird has gone. Ousu sheathes his sword and walks toward the village below. When morning comes, he plans to look for work.':'Ousu catches the prince’s fallen sword. They leave Yomi together and find a boat home at the shore.';
};
})();
