'use strict';
(() => {
const G=WB;
G.boundMoves={tide:['wave','tide','orochi'],ember:['ember_step'],wing:['feather'],jade:['mirror_guard'],mirror:['mirror_guard'],spear:['orb','tide','orochi'],hammer:['storm'],talisman:['storm'],comb:['orb','tide','orochi'],shaku:['storm'],flute:['feather'],divine:['feather','storm']};
G.syncWeapon=()=>{const p=G.p;if(!p)return;const signature=p.weapon+':'+p.weaponLevel+':'+p.weaponQuality;if(p.boundSignature===signature&&p.skillBag.every(s=>s.bound))return;p.boundSignature=signature;const ids=G.boundMoves[p.weapon],second=ids[Math.min(ids.length-1,Math.floor(p.weaponLevel/2))];p.skillBag=['weapon',second].map((id,i)=>({id,uid:'bound-'+i,q:p.weaponQuality||0,rank:Math.min(6,1+p.weaponLevel),bound:true}));p.activeSlots=p.skillBag.map(s=>s.uid);};
G.upgradeWeapon=(q=0)=>{const delta=.14+G.qualities[q].bonus*.4;G.p.weaponRolls.push(delta);G.p.weaponLevel++;G.p.weaponQuality=Math.max(G.p.weaponQuality,q);G.syncWeapon();G.event('weapon_reforged',{quality:q,rank:G.p.weaponLevel,moves:G.p.skillBag.map(s=>s.id)});};
G.rollQuality=(min=0)=>{const a=Math.min(4,G.act||0),weights=[.47-a*.09,.28-a*.025,.16+a*.035,.07+a*.05,.02+a*.03];let v=G.rng();for(let i=0;i<5;i++){v-=weights[i];if(v<0)return Math.max(min,i);}return 4;};
G.action=(kind,duration=.5)=>{if(G.p)G.p.action={kind,start:G.time,duration,until:G.time+duration};};
const start=G.start;G.start=(...a)=>{start(...a);G.p.moveFacing=1;G.syncWeapon();};
const acquire=G.acquireSkill;G.acquireSkill=(id,q,auto)=>{const old=G.p.skillBag.find(s=>s.id===id);if(old){old.rank=Math.min(6,old.rank+1);old.q=Math.max(old.q,q||0);return old;}return acquire(id,q,auto);};
G.ultimateName=()=>G.p.pathRank<2?'Homeward Wings · Tokoyo Crossing':G.p.path==='blood'?'Severance · Bloodbound Journey':'Divine Blade · Ame-no-Murakumo';
G.formIndex=()=>G.bloodActive()?2:G.p?.pathRank>=2?(G.p.path==='blood'?2:1):0;
const awaken=G.awaken;G.awaken=()=>{const p=G.p;if(G.state!=='running'||p.power<100||G.bloodActive())return;if(p.pathRank>=2){awaken();if(G.cinematic){G.cinematic.until=performance.now()+750;G.cinematic.name=G.ultimateName();}return;}p.power=0;p.inv=Math.max(p.inv,1.4);G.metrics.awakening_uses++;G.hostile=[];G.action('awaken',.7);G.cinematic={name:G.ultimateName(),line:'This time, the whitebird flies toward the human world.',art:'hero_long',until:performance.now()+700};for(const e of [...G.enemies])G.hit(e,210,'bird',true);G.effect(p.x,p.y,2,900,1.1);G.event('awakening',{path:p.path,rank:p.pathRank,form:'whitebird'});};
G.clearRoom=()=>{if(G.roomDone||G.ended)return;const n=G.currentNode;G.roomDone=true;G.state='running';G.hostile=[];G.zones=[];G.shots=[];G.enemies=[];if(n){n.cleared=true;n.rewardPending=true;n.rewardBoss=G.bossKey();}G.interactable={type:'reward_chest',x:720,y:430};if(n?.type==='boss')G.exitMarker={x:1110,y:625};G.drops.push({kind:'coin',x:760,y:460,value:G.roomType==='boss'?25:G.roomType==='elite'?15:8,r:12});const heal=2+G.lv('harvest')*2+(G.hasBless('kushinada')?8:0);G.p.hp=Math.min(G.p.maxHp,G.p.hp+heal*(G.hasBless('ibuki_curse')?.5:1));G.event('room_cleared',{act:G.act,node:n?.id,kind:n?.type,duration:G.roomTime});G.toast('Room cleared. A chest has appeared.');G.persist(true);};
const enterNode=G.enterNode;G.enterNode=(id,via)=>{const previous=G.currentNode;if(previous?.cleared)previous.floorDrops=structuredClone(G.drops.filter(d=>!d.taken));const ok=enterNode(id,via);if(!ok)return ok;const n=G.currentNode;G.exitMarker=n.cleared&&n.type==='boss'?{x:1110,y:625}:null;if(n.cleared){G.drops=structuredClone(n.floorDrops||[]);G.interactable=n.rewardPending?{type:'reward_chest',x:720,y:430}:null;}return ok;};
const interact=G.interact;G.interact=()=>{if(G.state!=='running')return;const n=G.currentNode,o=G.interactable;if(o?.type==='reward_chest'&&G.distance(G.p,o)<110&&n.rewardPending){G.event('reward_chest_opened',{node:n.id});const done=()=>{n.rewardPending=false;G.interactable=null;G.hideModal();G.state='running';G.persist(true);};const rewards=()=>['boss','ante'].includes(n.type)?G.offerRelic(()=>G.offerBlessing(done)):G.offerTalent(done,'chest_reward');if(['boss','ante'].includes(n.type))G.bossDialogue(n.rewardBoss,'after',rewards);else rewards();return;}if(G.exitMarker&&G.distance(G.p,G.exitMarker)<110){G.leaveChapter();return;}interact();};
const doors=G.drawDoors;G.drawDoors=ctx=>{if(G.currentNode?.cleared)doors(ctx);if(G.exitMarker){const {x,y}=G.exitMarker;ctx.save();ctx.drawImage(G.gateArt,x-63,y-120,126,148);ctx.fillStyle='#e9dcb8';ctx.textAlign='center';ctx.font='18px WhitebirdSans';ctx.fillText('Depart · E',x,y+38);ctx.restore();}};
const update=G.update;G.update=dt=>{if(!G.p)return update(dt);const p=G.p,m=G.moveVector();if(m.x)p.moveFacing=Math.sign(m.x);const positions=G.enemies.map(e=>[e,e.x,e.renderFacing]);G.syncWeapon();update(dt);p.renderFacing=p.moveFacing||1;for(const [e,x,face]of positions){const dx=e.x-x;e.renderFacing=Math.abs(dx)>.12?Math.sign(dx):face||1;}};
})();
