'use strict';
(() => {
const G=WB,canvas=G.$('#field'),ctx=canvas.getContext('2d'),W=G.W,H=G.H;
G.initializeBridge=()=>{if(G.ready&&G.uiReady)GameAgentBridge.register(G.bridgeTarget);};G.images={};G.sprites=[];G.heroSprites=[];G.effectTiles=[];G.shake=0;let scale=1,ox=0,oy=0;
const assets=['r2_kappa_elite','r2_tengu_elite','r2_inari_event','hero_long','hero_divine_v2','hero_blood_v2','hero_forms_v2','guardian_portrait','father_portrait','magatsu_portrait','prince_portrait','arena_shrine','arena_reeds','arena_tide','actors_atlas','items_atlas','boss_atlas','weapons_atlas','runes_atlas','clean_fx_atlas','orochi_fx','motion_hero','motion_divine','motion_blood','aragami_portrait','sea_portrait','arena_mountain','arena_sea','voyage_clean',"anim_kodama","anim_yomotsu","anim_fox","anim_soldier","anim_thunder","anim_wraith","anim_boar","anim_crab","anim_siren","anim_guardian","anim_father","anim_magatsu","anim_aragami","anim_sea","anim_fx_water","anim_fx_fire","anim_fx_bird"];
G.resize=()=>{const ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(innerWidth*ratio);canvas.height=Math.floor(innerHeight*ratio);canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';scale=Math.min(canvas.width/W,canvas.height/H);ox=(canvas.width-W*scale)/2;oy=(canvas.height-H*scale)/2;};
function cut(img,x,y,w,h,key=false){const c=document.createElement('canvas');c.width=w;c.height=h;const cx=c.getContext('2d',{willReadFrequently:true});cx.drawImage(img,x,y,w,h,0,0,w,h);if(key){let im=cx.getImageData(0,0,w,h),a=im.data;for(let i=0;i<a.length;i+=4){const r=a[i],g=a[i+1],b=a[i+2];if(r>160&&b>65&&r>g*1.65&&b>g*1.2){a[i+3]=0;}else if(r>130&&b>65&&r>g*1.4&&b>g*1.1){a[i+3]=120;a[i]=Math.min(r,g*1.5);}}const seen=new Uint8Array(w*h),q=new Int32Array(w*h);let head=0,tail=0;const offer=(n)=>{if(n<0||n>=w*h||seen[n])return;seen[n]=1;const k=n*4;if(a[k+3]===0||(a[k]>210&&a[k+1]>205&&a[k+2]>175&&Math.max(a[k],a[k+1],a[k+2])-Math.min(a[k],a[k+1],a[k+2])<65)){a[k+3]=0;q[tail++]=n;}};for(let xx=0;xx<w;xx++){offer(xx);offer((h-1)*w+xx);}for(let yy=0;yy<h;yy++){offer(yy*w);offer(yy*w+w-1);}while(head<tail){const n=q[head++];if(n%w)offer(n-1);if(n%w<w-1)offer(n+1);offer(n-w);offer(n+w);}const labels=new Int32Array(w*h);let label=0,best=0,bestSize=0;for(let seed=0;seed<w*h;seed++){if(labels[seed]||a[seed*4+3]<80)continue;label++;head=0;tail=0;q[tail++]=seed;labels[seed]=label;while(head<tail){const n=q[head++];for(let k=0;k<4;k++){const nn=k===0?(n%w?n-1:-1):k===1?(n%w<w-1?n+1:-1):k===2?n-w:n+w;if(nn>=0&&nn<w*h&&!labels[nn]&&a[nn*4+3]>=80){labels[nn]=label;q[tail++]=nn;}}}if(tail>bestSize){bestSize=tail;best=label;}}for(let n=0;n<w*h;n++)if(labels[n]!==best)a[n*4+3]=0;cx.putImageData(im,0,0);let minX=w,minY=h,maxX=0,maxY=0;for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++)if(a[(yy*w+xx)*4+3]>180){minX=Math.min(minX,xx);maxX=Math.max(maxX,xx);minY=Math.min(minY,yy);maxY=Math.max(maxY,yy);}if(maxX>minX){const tight=document.createElement('canvas');tight.width=maxX-minX+4;tight.height=maxY-minY+4;tight.getContext('2d').drawImage(c,minX-1,minY-1,tight.width,tight.height,0,0,tight.width,tight.height);return tight;}}return c;}
function prepare(){const img=G.images.actors_atlas,cols=[0,355,693,1024],rows=[0,416,704,1024];for(let i=0;i<9;i++){let col=i%3,row=Math.floor(i/3);G.sprites.push(cut(img,cols[col],rows[row],cols[col+1]-cols[col],rows[row+1]-rows[row],true));}
 const hero=G.images.hero_forms_v2;for(let i=0;i<3;i++)G.heroSprites.push(cut(hero,Math.floor(hero.width*i/3),0,Math.floor(hero.width/3),hero.height,true));
 const fx=G.images.clean_fx_atlas;for(let i=0;i<6;i++){let w=Math.floor(fx.width/3),h=Math.floor(fx.height/2);const tile=cut(fx,(i%3)*w,Math.floor(i/3)*h,w,h),cx=tile.getContext('2d');cx.globalCompositeOperation='destination-in';const gradient=cx.createRadialGradient(w/2,h/2,Math.min(w,h)*.26,w/2,h/2,Math.max(w,h)*.5);gradient.addColorStop(0,'#fff');gradient.addColorStop(1,'#fff0');cx.fillStyle=gradient;cx.fillRect(0,0,w,h);G.effectTiles.push(tile);}
}
Promise.all(assets.map(name=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{G.images[name]=img;resolve();};img.onerror=()=>reject(Error(name));img.src=`assets/${name}.png`;}))).then(()=>{G.images.voyage_atlas=G.images.voyage_clean;prepare();prepareMotion();prepareIsolated();prepareTransparent();G.ready=true;G.initializeBridge();Promise.resolve(G.journeyReady).then(()=>{G.$('#startBtn').disabled=false;G.$('#startBtn').textContent='Begin Journey →';}).catch(()=>{G.$('#startBtn').textContent='Assets failed to load. Please refresh the page.';});}).catch(e=>{G.$('#startBtn').textContent='Assets not loaded. Click to retry.';G.$('#startBtn').disabled=false;G.$('#startBtn').onclick=()=>location.reload();G.notice('Could not load '+e.message);});
G.formIndex=()=>G.p?.black?2:(G.p?.weaponLevel>=3||G.p?.awakenUntil>G.time)?1:0;
G.portrait=()=>['hero_long','hero_divine_v2','hero_blood_v2'][G.formIndex()];
G.iconHTML=(index,set='items',cls='')=>{const cols=set==='runes'?5:4,rows=set==='runes'?4:3,x=index%cols,y=Math.floor(index/cols);return `<span class="item-icon ${cls}" style="background-image:url('assets/${set==='voyage'?'voyage_clean':set+'_atlas'}.png');background-size:${cols*100}% ${rows*100}%;background-position:${x/(cols-1)*100}% ${y/(rows-1)*100}%"></span>`;};
G.particles=(x,y,color,n=5)=>{for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=25+Math.random()*80;G.fx.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,color,life:.3+Math.random()*.3,max:.6,r:2+Math.random()*2});}if(G.fx.length>300)G.fx.splice(0,G.fx.length-300);};
G.effect=(x,y,index,size=130,life=.4,rotation=0)=>{G.fx.push({x,y,index,size,life,max:life,rotation});if(G.fx.length>300)G.fx.shift();};
G.float=(x,y,text,color)=>G.fx.push({x,y,text,color,vy:-35,life:.9,max:.9});
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function legacyIcon(i,x,y,size=35,set='items'){const img=G.images[set+'_atlas'];if(!img)return;const cols=set==='runes'?5:4,rows=set==='runes'?4:3,w=img.width/cols,h=img.height/rows;ctx.save();ctx.globalCompositeOperation='screen';ctx.drawImage(img,i%cols*w,Math.floor(i/cols)*h,w,h,x-size/2,y-size/2,size,size);ctx.restore();}
function legacySprite(e,hero=false){const form=G.formIndex(),im=hero?G.heroSprites[form]:e.kind==='prince'?G.heroSprites[2]:G.sprites[e.sprite??2];if(!im)return;const moving=hero?(G.moveVector().x||G.moveVector().y):!e.windup,bob=moving?Math.sin(G.time*(hero?13:8)+e.x*.03)*2:0,height=hero?120:e.boss?(e.kind==='prince'?150:185):e.kind==='kodama'?84:102,width=height*im.width/im.height;
 ellipse(e.x,e.y+8,e.r*1.25,e.r*.38,'#03101890');
 if(hero){ctx.strokeStyle=form===2?'#de647c':'#96e6de';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(e.x,e.y+6,24,10,0,0,Math.PI*2);ctx.stroke();if(G.p.shield>0){ctx.strokeStyle='#c1e8d9a0';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(e.x,e.y-32,43,58,0,0,Math.PI*2);ctx.stroke();}}
 if(e.wet>0)ellipse(e.x,e.y+7,e.r+5,7,'#6ddade66');
 ctx.save();ctx.translate(e.x,e.y+bob+12);if(hero&&G.p.dx<-.2||!hero&&G.p.x<e.x)ctx.scale(-1,1);if(e.flash>0||hero&&G.p.inv>0&&Math.floor(G.time*15)%2)ctx.filter='brightness(1.7)';if(e.kind==='wraith')ctx.filter='hue-rotate(55deg)';ctx.drawImage(im,-width/2,-height,width,height);ctx.restore();
 if(!hero&&!e.boss&&e.hp<e.maxHp){ctx.fillStyle='#150d11c0';ctx.fillRect(e.x-22,e.y-height+5,44,4);ctx.fillStyle=e.kind==='seal'?'#f4d28c':'#d49087';ctx.fillRect(e.x-22,e.y-height+5,44*Math.max(0,e.hp/e.maxHp),4);}
 if(e.windup>0){ctx.strokeStyle='#ef6864';ctx.lineWidth=4;ctx.setLineDash([8,5]);ctx.beginPath();ctx.moveTo(e.x,e.y);ctx.lineTo(e.x+Math.cos(e.aim)*180,e.y+Math.sin(e.aim)*180);ctx.stroke();ctx.setLineDash([]);}
}
G.motion={};
function prepareMotion(){
 for(const name of ['motion_hero','motion_divine','motion_blood']){
  const im=G.images[name],rows=['motion_fx'].includes(name)?3:2;
  G.motion[name]=[];for(let row=0;row<rows;row++)for(let col=0;col<4;col++){const w=Math.floor(im.width/4),h=Math.floor(im.height/rows);G.motion[name].push(cut(im,col*w,row*h,w,h,name!=='motion_fx'));}
 }
}
function prepareIsolated(){for(const name of ["anim_kodama","anim_yomotsu","anim_fox","anim_soldier","anim_thunder","anim_wraith","anim_boar","anim_crab","anim_siren","anim_guardian","anim_father","anim_magatsu","anim_aragami","anim_sea","anim_fx_water","anim_fx_fire","anim_fx_bird"]){const im=G.images[name],w=Math.floor(im.width/2),h=Math.floor(im.height/2);G.motion[name]=[];for(let i=0;i<4;i++)G.motion[name].push(cut(im,i%2*w+(name==='anim_yomotsu'&&i%2===0?56:0),Math.floor(i/2)*h+(name==='anim_yomotsu'&&i<2?44:0),w-(name==='anim_yomotsu'&&i%2===0?56:0),h-(name==='anim_yomotsu'&&i<2?44:0),!name.startsWith('anim_fx')));}}
 function sprite(e,hero=false,forcedForm=null){
 if(G.modelFor?.(e,hero))return;
 const player=hero||e.kind==='prince'||e.kind==='whitebird',form=forcedForm??(hero?G.formIndex():e.kind==='whitebird'?1:2),moving=hero?(G.moveVector().x||G.moveVector().y):e.speed>0;
 let frame=0,sheet,row=0;
 if(player){sheet=['motion_hero','motion_divine','motion_blood'][form];const action=hero?G.p.action:e.action;if(e.dashTime>0||e.charge>0)frame=6;else if(action&&action.until>G.time){const t=(G.time-action.start)/action.duration;frame=action.kind==='cast'||action.kind==='awaken'?7:t<.3?3:t<.72?4:5;}else if(e.windup>0)frame=3;else if(moving)frame=1+Math.floor((e.walkTime||G.p.walkTime||0)*7)%2;else frame=0;}
 else{const mapping={kodama:[0],yomotsu:[1],fox:[2],soldier:[0],thunder:[1],wraith:[2],boar:[0],crab:[1],siren:[2],guardian:[0],father:[1],magatsu:[2],aragami:[0],sea:[1]};[sheet,row]=mapping[e.kind]||[0];
  const preparing=e.windup>0||e.castAnim>.25||e.attackAt-G.time<.35||e.godAt-G.time<.5;
  frame=e.charge>0||e.animUntil>G.time?3:preparing?2:e.walking?Math.floor((e.walkTime||0)*5)%2:0;sheet="anim_"+(e.kind==='ibuki_heaven'?'aragami':e.kind);
 }
 const beast=G.beastSprites?.[e.kind]&&(e.phaseForm==='beast'||e.kind==='ibuki_heaven');const beastFrame=e.charge>0?3:e.windup>0?2:e.action?.until>G.time?3:e.walking?Math.floor((e.walkTime||0)*4)%2:0;const im=G.poseFrame?.(e,hero,form)||(beast?G.beastSprites[e.kind][beastFrame]:G.motion[sheet]?.[frame]);if(!im){legacySprite(e,hero);return;}
 const height=hero?122:beast?(e.kind==='ibuki_heaven'?305:280):e.boss?(['prince','whitebird'].includes(e.kind)?195:235):e.kind==='kodama'?86:e.elite?130:104,width=height*im.width/im.height;
 ellipse(e.x,e.y+9,e.r*1.25,e.r*.38,'#03101890');
 if(hero){ctx.strokeStyle=form===2?'#e38998':'#9fe6df';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(e.x,e.y+7,25,10,0,0,Math.PI*2);ctx.stroke();if(G.p.shield>0){ctx.strokeStyle='#bbefec77';ctx.beginPath();ctx.ellipse(e.x,e.y-30,43,57,0,0,Math.PI*2);ctx.stroke();}}
 if(e.elite){ctx.strokeStyle='#f4c071';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(e.x,e.y+4,34,13,0,0,Math.PI*2);ctx.stroke();}
 ctx.save();const recoil=(e.recoil||e.hurtAnim||0)*35;ctx.translate(e.x+Math.cos(e.recoilA||0)*recoil,e.y+12+(0));if((hero?G.p.renderFacing:e.renderFacing)<0)ctx.scale(-1,1);if(e.dashTime>0)ctx.rotate(.1);if(e.flash>0||hero&&e.hurtAnim>0)ctx.filter='brightness(1.55)';ctx.drawImage(im,-width/2,-height,width,height);ctx.restore();
 if(!hero&&!e.boss&&e.hp<e.maxHp){ctx.fillStyle='#140f16b0';ctx.fillRect(e.x-22,e.y-height+2,44,4);ctx.fillStyle=e.elite?'#f4ce86':'#d4968a';ctx.fillRect(e.x-22,e.y-height+2,44*Math.max(0,e.hp/e.maxHp),4);}
 if(e.windup>0){ctx.strokeStyle='#ff9991';ctx.lineWidth=4;ctx.setLineDash([9,6]);ctx.beginPath();ctx.moveTo(e.x,e.y);ctx.lineTo(e.x+Math.cos(e.aim)*225,e.y+Math.sin(e.aim)*225);ctx.stroke();ctx.setLineDash([]);}
}
G.worldIcons={};
function alphaTile(im,background=true){const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0);const data=x.getImageData(0,0,c.width,c.height),a=data.data;for(let y=0;y<c.height;y++)for(let xx=0;xx<c.width;xx++){const n=(y*c.width+xx)*4,v=Math.max(a[n],a[n+1],a[n+2]);let alpha=G.clamp((v-55)/95,0,1);const edge=Math.min(xx,y,c.width-1-xx,c.height-1-y)/Math.min(c.width,c.height);alpha*=G.clamp((edge-.025)/.07,0,1);a[n+3]*=alpha;}x.putImageData(data,0,0);return c;}
function tightIcon(im){const a=im.getContext('2d').getImageData(0,0,im.width,im.height).data;let x0=im.width,y0=im.height,x1=0,y1=0;for(let y=0;y<im.height;y++)for(let x=0;x<im.width;x++)if(a[(y*im.width+x)*4+3]>80){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);}if(x1<=x0)return im;return cut(im,x0,y0,x1-x0+1,y1-y0+1);}
function cleanSea(im){const c=im.getContext('2d',{willReadFrequently:true}),w=im.width,h=im.height,d=c.getImageData(0,0,w,h),a=d.data,q=[],seen=new Uint8Array(w*h);const bg=n=>{const i=n*4;return a[i+3]<30||(Math.max(a[i],a[i+1],a[i+2])<85)||(a[i+1]>a[i]*1.25&&a[i+2]>a[i]*1.3&&a[i]<50);};const add=n=>{if(n<0||n>=w*h||seen[n]||!bg(n))return;seen[n]=1;a[n*4+3]=0;q.push(n);};for(let x=0;x<w;x++){add(x);add((h-1)*w+x);}for(let y=0;y<h;y++){add(y*w);add(y*w+w-1);}for(let i=0;i<q.length;i++){const n=q[i];if(n%w)add(n-1);if(n%w<w-1)add(n+1);add(n-w);add(n+w);}c.putImageData(d,0,0);return im;}
function prepareTransparent(){for(const k of ['anim_wraith','anim_siren','anim_crab'])G.motion[k]=G.motion[k].map(cleanSea);for(const set of ['items','voyage','weapons','runes','boss']){const im=G.images[set+'_atlas'];if(!im)continue;const cols=set==='runes'?5:4,rows=set==='runes'?4:3;G.worldIcons[set]=[];for(let i=0;i<cols*rows;i++){const w=Math.floor(im.width/cols),h=Math.floor(im.height/rows);G.worldIcons[set].push(tightIcon(alphaTile(cut(im,i%cols*w,Math.floor(i/cols)*h,w,h))));}}for(const key of ['anim_fx_water','anim_fx_fire','anim_fx_bird'])G.motion[key]=G.motion[key].map(im=>alphaTile(im));G.effectTiles=G.effectTiles.map(im=>alphaTile(im));G.images.orochi_fx=alphaTile(G.images.orochi_fx);}
function icon(i,x,y,size=35,set='items'){const im=G.worldIcons[set]?.[i];if(!im)return;ctx.save();ctx.globalCompositeOperation='source-over';ctx.drawImage(im,x-size/2,y-size/2,size,size);ctx.restore();}
function drawEnemyEffects(){for(const f of G.enemyFx||[]){const t=G.clamp((G.time-f.start)/f.duration,0,1);if(t>=1)continue;if(G.drawEnemyEffectFrame?.(ctx,f,t))continue;ctx.save();ctx.globalAlpha=Math.sin(Math.PI*t)*.85;ctx.strokeStyle=f.color;ctx.fillStyle=f.color;ctx.shadowColor=f.color;ctx.shadowBlur=14;ctx.lineWidth=5*(1-t)+2;if(f.kind==='tide'){for(let i=0;i<3;i++){ctx.beginPath();for(let x=80;x<1360;x+=16){const y=f.y+Math.sin(x*.018-t*8+i)*12+(t-.5)*85+i*9;x===80?ctx.moveTo(x,y):ctx.lineTo(x,y);}ctx.stroke();}}else if(f.kind==='thunder'){for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(f.x-20+i*20,f.y-190);ctx.lineTo(f.x+25-i*15,f.y-105);ctx.lineTo(f.x-15+i*12,f.y-70);ctx.lineTo(f.x,f.y);ctx.stroke();}}else if(f.kind==='slash'){ctx.translate(f.x,f.y);ctx.rotate(f.a||0);ctx.beginPath();ctx.arc(0,0,45+t*105,-1.1,1.1);ctx.stroke();}else{ctx.beginPath();ctx.ellipse(f.x,f.y,20+t*f.r,8+t*f.r*.5,0,0,Math.PI*2);ctx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4+t;ctx.beginPath();ctx.moveTo(f.x+Math.cos(a)*t*f.r,f.y+Math.sin(a)*t*f.r*.5);ctx.lineTo(f.x+Math.cos(a)*(t*f.r+18),f.y+Math.sin(a)*(t*f.r+18)*.5);ctx.stroke();}}ctx.restore();}}

function animatedEffect(f,alpha){
 const row=f.index===1?1:f.index===2||f.index===5?2:0,frame=Math.min(3,Math.floor((1-alpha)*4)),im=G.generatedFx?.(f.index,1-alpha)||G.motion[["anim_fx_water","anim_fx_fire","anim_fx_bird"][row]]?.[frame];
 if(!im){tile(f.index,f.x,f.y,f.size,alpha,f.rotation);return;}
 ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=Math.min(1,alpha*1.8);ctx.translate(f.x,f.y);ctx.rotate((f.rotation||0)+(1-alpha)*(f.index===0?.35:.08));const size=f.size*(.8+(1-alpha)*.35);ctx.drawImage(im,-size/2,-size/2,size,size);ctx.restore();
 if(!G.fx6?.fx_combat_v6&&(f.index===3||f.index===4))tile(f.index,f.x,f.y,f.size*.9,alpha*.6,(f.rotation||0)+G.time*.4);
}

function tile(index,x,y,size,alpha=1,rotation=0){const img=G.effectTiles[index];if(!img)return;ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.rotate(rotation);ctx.drawImage(img,-size/2,-size/2,size,size);ctx.restore();}
G.draw=dt=>{
 if(!G.ready||!G.p)return;ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#060c11';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.setTransform(scale,0,0,scale,ox,oy);ctx.save();if(G.shake>0){ctx.translate((Math.random()-.5)*G.shake,(Math.random()-.5)*G.shake);G.shake=Math.max(0,G.shake-dt*35);}
 const region=G.regions[Math.min(G.regions.length-1,G.act)];ctx.save();if(G.currentNode?.flip){ctx.translate(W,0);ctx.scale(-1,1);}ctx.drawImage(G.images[region.art],0,0,W,H);ctx.restore();ctx.fillStyle=G.act===2?'#160c242c':'#06131730';ctx.fillRect(0,0,W,H);
 G.drawScenery?.(ctx);G.drawDoors?.(ctx);
 // Paint a fallback only while the 3D scenery layer is unavailable.
 for(const o of G.drawScenery?[]:G.obstacles){ellipse(o.x,o.y+15,o.r*1.2,o.r*.65,'#04101880');const g=ctx.createRadialGradient(o.x-12,o.y-15,5,o.x,o.y,o.r*1.2);g.addColorStop(0,'#738e84');g.addColorStop(.5,'#334e4b');g.addColorStop(1,'#142e2e');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(o.x-o.r,o.y);ctx.lineTo(o.x-o.r*.6,o.y-o.r*.7);ctx.lineTo(o.x+o.r*.4,o.y-o.r);ctx.lineTo(o.x+o.r,o.y+o.r*.15);ctx.lineTo(o.x+o.r*.4,o.y+o.r*.5);ctx.lineTo(o.x-o.r*.6,o.y+o.r*.5);ctx.closePath();ctx.fill();}
 for(const grass of G.grass||[]){ctx.strokeStyle=grass.burning>0?'#e7a55888':G.act===1?'#bea361a0':'#77968970';ctx.lineWidth=2;for(let i=0;i<14;i++){let x=grass.x+Math.sin(i*7.3)*grass.r,y=grass.y+Math.cos(i*4.2)*grass.r*.4;ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x-6,y-15,x+Math.sin(G.time+i)*4,y-27-(i%4)*4);ctx.stroke();}if(grass.burning>0)tile(1,grass.x,grass.y,grass.r*2.2,.7);}
 for(const z of G.zones){if(z.friend&&G.drawInkZone?.(ctx,z))continue;if(z.friend){if(z.vortex)tile(4,z.x,z.y,z.r*2,.6,G.time*.5);else if(!z.once)tile(1,z.x,z.y,z.r*2,.7);continue;}const ready=z.age/z.delay;ctx.fillStyle=`rgba(155,32,61,${.12+Math.min(1,ready)*.2})`;ctx.strokeStyle=z.ritual==='edict'?'#e6c27c':ready>.8?'#ffb7a0':'#ff6471';if(z.ritual==='edict')ctx.fillStyle='rgba(216,176,82,.18)';ctx.lineWidth=3;ctx.setLineDash([10,6]);if(z.kind==='line'){ctx.fillRect(z.x-48,165,96,H-280);ctx.strokeRect(z.x-48,165,96,H-280);}else if(z.kind==='hline'){ctx.fillRect(75,z.y-48,W-150,96);ctx.strokeRect(75,z.y-48,W-150,96);}else{ctx.beginPath();ctx.arc(z.x,z.y,z.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(z.x,z.y,z.r*Math.min(1,ready),0,Math.PI*2);ctx.stroke();}ctx.setLineDash([]);}
 if(G.interactable&&!G.hasSceneryObject?.(G.interactable.type)){let o=G.interactable;tile(5,o.x,o.y,170,.4);icon(o.type==='shop'?10:o.type==='forge'?11:o.type==='shrine'?5:9,o.x,o.y-20,92,o.type==='shop'?'voyage':'items');ctx.font='18px WhitebirdSans';ctx.textAlign='center';ctx.fillStyle='#fff0c8';ctx.fillText({forge:'Flint Forge',shrine:'Sanctuary',event:'Nameless Traveler',shop:'Lantern Merchant',camp:'Stillwind Garden'}[o.type]||G.roomNames[o.type]||'Depart',o.x,o.y+45);}
 for(const drop of G.drops){if(drop.kind==='chest'&&G.hasSceneryObject?.('chest'))continue;if(drop.kind==='xp'){ellipse(drop.x,drop.y,6,4,'#acf0d4');ellipse(drop.x,drop.y,2,2,'#f2fff1');}else if(['coin','chest','essence'].includes(drop.kind)){ellipse(drop.x,drop.y,drop.kind==='chest'?21:13,7,drop.kind==='coin'?'#e7bd5640':'#86cfdf35');icon(drop.kind==='coin'?0:drop.kind==='chest'?1:6,drop.x,drop.y-8+Math.sin(G.time*4)*3,drop.kind==='chest'?48:30,'voyage');if(drop.kind==='chest'){ctx.fillStyle='#ffe8b6';ctx.font='14px WhitebirdSans';ctx.textAlign='center';ctx.fillText('Chest',drop.x,drop.y-40);}}else icon(drop.kind==='rice'?9:10,drop.x,drop.y-8,38);}
 for(const s of G.shots){if(G.drawProjectileFrame?.(ctx,s))continue;if(s.orb){tile(4,s.x,s.y,85,.85,G.time);continue;}ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.a);ctx.shadowColor=s.element==='fire'?'#fdb16a':s.element==='bird'?'#f3e8c2':'#66ddd8';ctx.shadowBlur=12;const tail=ctx.createLinearGradient(-60,0,16,0);tail.addColorStop(0,'#ffffff00');tail.addColorStop(1,ctx.shadowColor);ctx.fillStyle=tail;ctx.beginPath();ctx.moveTo(-65,0);ctx.lineTo(6,-6);ctx.lineTo(6,6);ctx.closePath();ctx.fill();ctx.fillStyle=ctx.shadowColor;ctx.beginPath();ctx.moveTo(20,0);ctx.quadraticCurveTo(0,-10,-24,0);ctx.quadraticCurveTo(0,6,20,0);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff7df';ctx.fillRect(-9,-1,23,2);ctx.restore();}
 for(const ghost of G.ghosts||[]){ctx.save();ctx.globalAlpha=ghost.life/.22*.28;sprite({...G.p,...ghost,dashTime:1},true,ghost.form);ctx.restore();}
 for(const dead of G.deaths||[]){ctx.save();ctx.globalAlpha=dead.life/.4;ctx.translate(dead.x,dead.y);ctx.rotate((1-dead.life/.4)*.45);ctx.translate(-dead.x,-dead.y);if(!G.r2DrawElite?.(ctx,dead,true))sprite(dead);ctx.restore();}
 const entities=[...G.enemies.filter(e=>!e.dead),{...G.p,hero:true}].sort((a,b)=>a.y-b.y);for(const e of entities){if(G.r2DrawElite?.(ctx,e))continue;if(e.kind==='seal'){tile(5,e.x,e.y,85,.65,G.time*.2);icon(5,e.x,e.y-15,65);ctx.fillStyle='#f1d59a';ctx.font='17px WhitebirdSans';ctx.textAlign='center';ctx.fillText('Edict',e.x,e.y-7);}else sprite(e,e.hero);}
 G.drawBossFx?.(ctx);G.drawPaintedFx?.(ctx);G.drawActorAttributes?.(ctx);
 const orbitCount=G.lv('orbit');for(let i=0;i<orbitCount;i++){const a=G.time*2.8+i*Math.PI*2/orbitCount;icon(0,G.p.x+Math.cos(a)*98,G.p.y+Math.sin(a)*98,45);}
 for(let i=0;i<(G.extraOrbits||0);i++){const a=G.time*2.6+i*Math.PI*2/G.extraOrbits;icon(G.p.weapon==='jade'?3:2,G.p.x+Math.cos(a)*135,G.p.y+Math.sin(a)*135,30);}
 const runeSwords=G.p.rune==='orbit'?2:0,runeOrbits=runeSwords+(G.p.weapon==='jade'?3:0);for(let i=0;i<runeOrbits;i++){const a=G.time*2.5+i*Math.PI*2/runeOrbits;icon(i<runeSwords?0:3,G.p.x+Math.cos(a)*100,G.p.y+Math.sin(a)*100,i<runeSwords?45:35);}
 if(G.has('bead'))for(let i=0;i<3;i++){const a=G.time*2+i*Math.PI*2/3;icon(3,G.p.x+Math.cos(a)*75,G.p.y+Math.sin(a)*75,35);}
 for(const s of G.hostile){ellipse(s.x,s.y,12,12,s.color?'#cfb47750':'#a8316250');ellipse(s.x,s.y,7,7,s.color||'#f68b9c');ellipse(s.x-1,s.y-1,3,3,'#ffe6bb');}
 for(const b of G.beams||[]){if(b.water&&G.fx6?.fx_combat_v6)continue;ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.a);ctx.globalAlpha=b.life/b.max;ctx.globalCompositeOperation='screen';ctx.shadowBlur=30;ctx.shadowColor=b.water?'#68e5e3':'#ffe8a9';const gradient=ctx.createLinearGradient(0,0,1300,0);gradient.addColorStop(0,b.water?'#7efaf8':'#fff9d5');gradient.addColorStop(1,'#fff0');ctx.fillStyle=gradient;ctx.fillRect(0,-b.width/2,1400,b.width);ctx.fillStyle='#fff7e8';ctx.fillRect(0,-b.width*.08,1200,b.width*.16);ctx.restore();}
 for(const f of G.fx){if(G.state==='running'){f.life-=dt;if(f.vx){f.x+=f.vx*dt;f.y+=f.vy*dt;}else if(f.vy)f.y+=f.vy*dt;}let alpha=G.clamp(f.life/f.max,0,1);if(f.index!==undefined){animatedEffect(f,alpha);}else if(f.orochi&&G.drawInkSerpent){G.drawInkSerpent(ctx,f,alpha);}else if(f.orochi){ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=Math.min(1,alpha*2);ctx.drawImage(G.images.orochi_fx,f.x-f.size/2,f.y-f.size/2,f.size,f.size);ctx.restore();}else if(f.line){ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle='#d4d3ff';ctx.shadowColor='#8e9dff';ctx.shadowBlur=12;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(f.x,f.y);ctx.lineTo((f.x+f.x2)/2+12,(f.y+f.y2)/2-18);ctx.lineTo(f.x2,f.y2);ctx.stroke();ctx.restore();}else{ctx.globalAlpha=alpha;if(f.text){ctx.font='bold 18px WhitebirdSans';ctx.textAlign='center';ctx.strokeStyle='#09151a';ctx.lineWidth=3;ctx.strokeText(f.text,f.x,f.y);ctx.fillStyle=f.color;ctx.fillText(f.text,f.x,f.y);}else ellipse(f.x,f.y,f.r,f.r,f.color);ctx.globalAlpha=1;}}G.fx=G.fx.filter(f=>f.life>0);
 // Atmospheric particles stay subordinate to the red danger telegraphs.
 ctx.strokeStyle=G.act===1?'#e9cc841c':'#abd9dc20';ctx.lineWidth=1;for(let i=0;i<45;i++){let x=(i*163-G.time*30)%W;if(x<0)x+=W;let y=(i*83+G.time*(G.act===1?40:240))%H;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-3,y+(G.act===1?3:12));ctx.stroke();}
 drawEnemyEffects();const v=ctx.createRadialGradient(W/2,H/2,280,W/2,H/2,900);v.addColorStop(0,'#050f1600');v.addColorStop(1,'#020b17b0');ctx.fillStyle=v;ctx.fillRect(0,0,W,H);ctx.restore();
};
let last=performance.now(),hud=0;
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(G.state!=='home'){G.update(dt);G.draw(dt);}if(now>hud){G.updateHud?.();hud=now+100;}requestAnimationFrame(loop);}
G.resize();requestAnimationFrame(loop);
})();
