'use strict';
(() => {
const G=WB,$=G.$;let choiceAt=0,noticeTimer,toastTimer,audio;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
G.beep=(f=400,d=.1)=>{if(!G.sound||!audio)return;try{const o=audio.createOscillator(),a=audio.createGain();o.type='sine';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*.6,audio.currentTime+d);a.gain.setValueAtTime(.018,audio.currentTime);a.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(a);a.connect(audio.destination);o.start();o.stop(audio.currentTime+d);}catch{}};
function unlock(){if(!audio)try{audio=new(window.AudioContext||window.webkitAudioContext)();}catch{}audio?.resume?.();}
G.notice=t=>{$('#notice').textContent=t;$('#notice').classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').classList.remove('show'),3600);};
G.toast=t=>{$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2300);};
G.activate=id=>document.querySelectorAll('.screen').forEach(n=>n.classList.toggle('active',n.id===id));
G.hideModal=()=>{$('#overlay').hidden=true;$('#modal').innerHTML='';$('#modal').className='modal';G.keys.clear();};
G.modal=(html,cls='')=>{G.keys.clear();$('#modal').className='modal '+cls;$('#modal').innerHTML=html;$('#overlay').hidden=false;$('#modal').scrollTop=0;};
G.offer=(title,subtitle,options,then,context='choice',skip=null)=>{
 G.state='choice';G.choiceId++;choiceAt=performance.now();G.choice={id:G.choiceId,options,then,context};G.event('choice_offered',{choice_id:G.choiceId,context,options:options.map(({id,name,text,tags,effect,disabled})=>({id,name,text,tags:tags||[],effect:effect||{},disabled:!!disabled})),player:{hp:G.p.hp,max_hp:G.p.maxHp,build:{...G.p.talents},weapon:G.p.weapon,rune:G.p.rune,gold:G.p.gold,equipped_relics:[...G.p.equipped||[]],relic_ranks:{...G.p.relicRanks},act:G.act,stage:G.stage}});
 const many=options.length>4;G.modal(`<div class="eyebrow">${context==='starting_weapon'?'Departure':context==='core_rune'?'Blade Inscription':'Gift of Tokoyo'}</div><h2>${title}</h2><p class="modal-sub">${subtitle}</p><div class="cards ${many?'many':''}">${options.map((c,i)=>`<button class="card ${c.rare?'rare':''}" data-choice="${i}" ${c.disabled?'disabled':''}>${G.iconHTML(c.icon||0,c.iconSet||'items')}<small>${esc(c.tag||c.family||(c.rare?'Mythic Relics':'A Choice on the Road'))}</small><h3>${esc(c.name)}</h3><p>${esc(c.text)}</p><kbd>${i<9?'[ '+(i+1)+' ]':'Click'} ${c.disabled?'Not enough coins / HP':'Choose'}</kbd></button>`).join('')}</div><div class="modal-foot"><span>Combat paused · ${many?'Scroll to see all options':'Click or press a number key'}</span>${skip?'<button id="skipChoice" class="secondary">Keep Your Coins and Leave</button>':''}</div>`,(many?'wide choices-wide':'')+(context==='shop'?' shop-choice':''));
 document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>G.choose(+b.dataset.choice));if(skip)$('#skipChoice').onclick=()=>{G.event('choice_skipped',{choice_id:G.choice.id});G.choice=null;G.hideModal();skip();};
};
G.choose=i=>{if(G.state!=='choice'||!G.choice||!G.choice.options[i]||G.choice.options[i].disabled)return;const c=G.choice.options[i],then=G.choice.then;G.event('choice_selected',{choice_id:G.choice.id,option_id:c.id,decision_ms:Math.round(performance.now()-choiceAt)});G.metrics.choices++;G.choice=null;G.hideModal();G.beep(720,.12);then(c);G.persist(true);};
G.uiStory=(act,then)=>{
 const region=G.regions[act],words=[['Protect the Villagers','Tonight, I’ll save the people who are still alive.'],['I Choose Where I Go','You gave me a name. You cannot live my life for me.'],['Change the Journey with This Sword','The old tale can remember my death. I’ll live to see another dawn.']][act];
 G.offer(region.name,region.intro,[{id:'self',name:words[0],icon:2,text:'Autonomy +1. Max HP +8. Restore 12 HP.',effect:{autonomy:1,maxHp:8,heal:12},tags:['narrative','autonomy','survival']},{id:'command',name:'Borrow the Emperor’s Power',icon:0,text:'Imperial echo +1. All damage +10%. Lose 5 current HP, never fatal. Two echoes unlock Bloodrage and the former-self branch.',effect:{obedience:1,damage:.1,hp:-5},tags:['narrative','obedience','risk']}],c=>{
  if(c.id==='self'){G.autonomy++;G.p.maxHp+=8;G.p.hp=Math.min(G.p.maxHp,G.p.hp+12);G.toast(words[1]);}else{G.obedience++;G.p.damage+=.1;G.p.hp=Math.max(1,G.p.hp-5);}
  G.p.blackUnlocked=G.obedience>=2||G.has('blood_wrap');G.event('narrative_choice',{act,choice:c.id,autonomy:G.autonomy,obedience:G.obedience});
  if(act===2&&G.p.blackUnlocked)G.offer('Who Looks Back from the Sea?','The old command echoes within you. Choose whom you face ahead.',[{id:'prince',name:'Face the Bloodstained Prince',icon:0,text:'Enter the former-self branch. Face the version of yourself controlled by imperial command, and sever the puppet strings.',effect:{shadow_final:true},tags:['hidden_boss','selfhood']},{id:'magatsu',name:'Purge Magatsu',icon:6,text:'Follow the path through Tokoyo and face the Tide of Magatsu.',effect:{shadow_final:false},tags:['main_boss','protection']}],v=>{G.shadowFinal=v.id==='prince';then();},'final_path');else then();
 },'narrative');
 $('#modal').classList.add('story-modal');$('#modal').insertAdjacentHTML('afterbegin',`<img class="story-art" src="assets/${act===0?'hero_long':act===1?'father_portrait':'hero_divine_v2'}.png" alt="Chapter artwork"><span class="chapter-numeral">${['I','II','III'][act]}</span>`);
};
G.uiBoss=then=>{G.state='boss_intro';G.choice=null;const b=G.boss;G.modal(`<div class="boss-art" style="background-image:url('assets/${b.kind==='prince'?'hero_blood_v2':b.art}.png')"></div><div class="boss-copy"><div class="eyebrow">${b.title}</div><h2>${b.name}</h2><blockquote>${b.line}</blockquote><p>${b.tip}</p><button class="primary" id="bossStart">Draw Your Sword <span>→</span></button><small>Press Enter to begin. You cannot be hurt during the introduction.</small></div>`,'boss-modal');$('#bossStart').onclick=()=>{G.event('boss_intro_completed',{kind:b.kind});then();};};
function mapMarkup(){return `<div class="journey-map">${G.regions.map((r,a)=>`<div class="map-act ${a===G.act?'current':''}"><small>No. ${a+1} Chapter</small><h3>${r.name}</h3><div class="map-nodes">${['Purification','Merchant / Forge / Sanctuary / Encounter','Quiet Path / Dangerous Path',a===G.regions.length-1&&G.shadowFinal?'Bloodstained Prince':'Wild Spirit'].map((name,s)=>{const visit=G.route.find(v=>v.act===a&&v.stage===s);return `<div class="map-node ${visit?'visited':''} ${a===G.act&&s===G.stage?'here':''}"><i>${visit?'◆':'◇'}</i><span>${visit?({battle:'Purification Grounds',elite:'Wild Spirit Trial',forge:'Flint Forge',shrine:'Sanctuary',event:'Chance Encounter',shop:'Lantern Merchant',boss:name}[visit.type]):name}</span></div>`;}).join('<span class="map-link"></span>')}</div></div>`).join('')}</div>`;}
G.uiRoute=options=>{G.offer('Choose your next path.','Rewards shape your build. Both paths lead to this chapter’s wild spirit.',options,c=>{if(c.id==='boss')G.p.hp=Math.min(G.p.maxHp,G.p.hp+15);G.enterRoom(c.id);},'room_route');$('#modal').insertAdjacentHTML('afterbegin',mapMarkup());$('#modal').classList.add('route-modal');};
G.showMap=()=>{if(!['running','paused'].includes(G.state))return;const before=G.state;G.state='map';G.event('map_opened');G.modal(`<div class="eyebrow">Homeward Journey · Current Route</div><h2>Each step changes the old tale.</h2>${mapMarkup()}<p>Choose the next room after combat. Forges upgrade equipment, sanctuaries improve talents, and encounters exchange resources.</p><button class="primary" id="backMap">Return to Journey</button>`,'wide');$('#backMap').onclick=()=>{G.hideModal();if(before==='paused')G.pause();else G.state='running';};};
G.pause=(reason='manual')=>{if(!['running','paused','map','character'].includes(G.state))return;G.state='paused';G.event('pause',{reason});G.modal(`<div class="eyebrow">Whitebird at Rest</div><h2>Take a moment to rest.</h2><p>WASD  Move · Space Dash · F / R Techniques · Q Awakening<br>C  Character · M Map</p><div class="actions"><button class="primary" id="resumeBtn">Resume →</button><button class="secondary" id="endBtn">End Run and Leave Feedback</button></div>`);$('#resumeBtn').onclick=G.resume;$('#endBtn').onclick=()=>G.finish('abandoned');};
G.resume=()=>{G.state='running';G.hideModal();G.event('resume');};
G.character=()=>{if(!['home','running','paused'].includes(G.state))return;const previous=G.state;G.state=previous==='home'?'home':'character';if(G.session&&!G.ended)G.event('character_opened');let tab='stats';
 const close=()=>{G.hideModal();if(previous==='paused')G.pause();else G.state=previous;};
 function paint(){const p=G.p&&!G.ended?G.p:null,portrait=p?G.portrait():'hero_long';G.modal(`<div class="character-shell"><aside class="character-art"><img src="assets/${portrait}.png" alt="Current character form"><div><small>Whitebird Soul</small><h2>Ousu-no-Mikoto</h2><p>${p?.black?'Bloodrage · Echo of the Emperor':p?.weaponLevel>=3?'Divine · Murakumo Unleashed':'Ousu · A Journey of His Own'}</p></div></aside><section class="character-content"><div class="character-top"><div class="eyebrow">Character Journal</div><button id="closeCharacter" class="ghost">Close ×</button></div><nav class="tabs">${[['stats','Stats'],['gear','Weapons & Relics'],['skills','Active / Passive'],['talents','Talents'],['library','240 Build Codex']].map(([id,name])=>`<button data-tab="${id}" class="${tab===id?'active':''}">${name}</button>`).join('')}</nav><div id="tabBody"></div></section></div>`,'character-modal wide');$('#closeCharacter').onclick=close;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;paint();});let body='';
 if(tab==='stats'){body=`<h2>${p?'Your Current Form':'Ousu-no-Mikoto'}</h2><p>${p?G.recipe(p.weapon,p.rune||'echo'):'On this journey, choose your weapon, inscription and talents. Each return offers another chance to change the tragedy.'}</p><div class="stat-grid">${(p?[['HP',`${Math.ceil(p.hp)} / ${p.maxHp}`],['All-Damage Multiplier',G.power().toFixed(2)+'×'],['Move Speed',p.speed],['Armor Reduction',p.armor+G.lv('ward')],['Shields',p.shield],['Coins',p.gold],['Autonomy',G.autonomy],['Imperial Echoes',G.obedience+'/2']]:[['Weapons',12],['Core Inscription',20],['Base Combination',240],['Region',3]]).map(([label,value])=>`<div><small>${label}</small><strong>${value}</strong></div>`).join('')}</div><p class="note">${p?.blackUnlocked?'Bloodrage unlocked: press T in combat to toggle. Damage +40%. Lose 1.5 HP per second, never below 1.':'Weapon upgrade +3 awakens white hair streaks and golden eyes. Two imperial echoes let you confront your former self.'}</p>`;}
 if(tab==='gear'){const w=p?G.form():G.weapons[0];body=`<h2>Weapon · ${w.name}</h2><div class="equipment-main">${G.iconHTML(w.icon,'weapons')}<div><h3>${p?'+ '+p.weaponLevel:'Not Yet Departed'}</h3><p>${w.text}</p></div></div><div class="evolution"><span>First Awakening<br>Wide-Area Sword Art</span><i>→</i><span class="${p?.weaponLevel>=1?'lit':''}">+1 Temper<br>Ignite the Reeds</span><i>→</i><span class="${p?.weaponLevel>=3?'lit':''}">+3 Divine Armament<br>Light Beam / Divine Form</span></div><h3>Armor · ${p?'Upgrade +'+p.armorLevel:'Old Bronze Armor'}</h3><p>Mend armor at the Flint Forge to reduce damage taken, increase max HP and restore HP.</p><h3>Carried Relic</h3><div class="item-list">${(p?p.relics.map(id=>G.relics.find(r=>r.id===id)):G.relics).map(r=>`<article>${G.iconHTML(r.icon,r.iconSet||'items')}<div><b>${r.name}</b><p>${r.text}</p></div></article>`).join('')||'<p>Dangerous paths and boss rooms award mythic relics.</p>'}</div>`;}
 if(tab==='skills'){body=`<h2>Active Techniques</h2><div class="item-list"><article>${G.iconHTML(0)}<div><b>F · Kusanagi Slash / Weapon Technique</b><p>Use your weapon’s unique attack. Upgrades ignite reeds; +3 unlocks a light beam.</p></div></article><article>${G.iconHTML(2)}<div><b>Space · Featherstep / Q · Whitebird Crossing</b><p>Dashing grants brief invulnerability and cuts through enemies. Awakening consumes 100 charge, clears projectiles, deals area damage and briefly enters Divine form.</p></div></article></div><h3>R · Equip a Water Art</h3><div class="water-list">${G.waterArts.map(a=>{const enabled=p&&G.lv('water')>=a.level;return `<button data-water="${a.id}" ${!enabled?'disabled':''} class="${p?.waterArt===a.id?'selected':''}">${G.iconHTML(a.icon)}<b>${a.name}</b><p>${a.text}</p><small>${p?.waterArt===a.id?'Equipped':enabled?'Click to Equip':`Requires Tide rank ${a.level}  Rank`} · ${a.cd}  s</small></button>`;}).join('')}</div><h3>Passive Effect</h3><p>${p?G.recipe(p.weapon,p.rune||'echo'):'Choose a weapon and inscription to view your current combination.'}</p>`;}
 if(tab==='talents'){body=`<h2>Talents & Synergies</h2><p>Fire evaporates Wet effects. Steam Sea spreads the resulting blast to nearby enemies. Inscriptions and talents can stack.</p><div class="talent-grid">${G.talents.map(t=>`<article class="${p&&G.lv(t.id)?'learned':''}">${G.iconHTML(t.icon)}<div><b>${t.name} <small>${p?G.lv(t.id):0} / ${t.max}</small></b><p>${t.text}</p>${t.requires?`<small>Requires: ${t.requires==='fusion'?'Tide and Flame rank 1':G.talents.find(x=>x.id===t.requires)?.name+' 1  Rank'}</small>`:''}</div></article>`).join('')}</div>`;}
 if(tab==='library'){body=`<h2>Twelve Weapons × Twenty Inscriptions</h2><p>240  base combinations can be selected at the start. This preview does not change your equipment.</p><label>Weapon <select id="libraryWeapon">${G.weapons.map(w=>`<option value="${w.id}">${w.name}</option>`).join('')}</select></label><div id="combinationGrid" class="combination-grid"></div>`;}
 $('#tabBody').innerHTML=body;if(tab==='skills')document.querySelectorAll('[data-water]').forEach(b=>b.onclick=()=>{p.waterArt=b.dataset.water;G.event('water_art_equipped',{id:p.waterArt,reason:'player_choice'});paint();});if(tab==='library'){const update=()=>{const id=$('#libraryWeapon').value;$('#combinationGrid').innerHTML=G.runes.map(r=>`<article>${G.iconHTML(r.icon,'runes')}<div><b>${r.name}</b><p>${G.recipe(id,r.id)}</p></div></article>`).join('');};update();$('#libraryWeapon').onchange=update;}
 }paint();
};
G.uiResult=()=>{const win=G.session.status==='victory',s=G.summary();G.modal(`<div class="result-layout"><img src="assets/${win?'hero_divine_v2':G.portrait()}.png" alt="Homeward Path"><section><div class="eyebrow">${win?'Homeward Journey · Chapter’s End':'Whitebird Returns · Journey Recorded'}</div><h2>${win?(G.shadowFinal?'The Eastern Campaign Is Over':'I’m back.'):G.session.status==='defeat'?'Journey’s End':'Run Ended'}</h2><p>${win?(G.shadowFinal?'The prince’s shadow scatters into white feathers. The commands stained into the sword fall silent. The past remains, but tomorrow is yours to choose.':'The tide recedes. The whitebird turns away from the sky of the dead. You follow the old road back to the living. The ancient ending remains in the book. You have stepped beyond it.'):'An unfinished journey leaves something to carry into the next.'}</p><div class="result-stats"><span>Kills <b>${s.kills}</b></span><span>Bosses <b>${s.bosses_defeated} / ${G.regions.length}</b></span><span>Visited <b>${s.rooms}  rooms</b></span><span>Combat <b>${Math.floor(G.time/60)}:${String(Math.floor(G.time%60)).padStart(2,'0')}</b></span></div><p class="build-summary">${G.recipe(G.p.weapon,G.p.rune||'echo')}</p><form id="feedbackForm"><label>What did you enjoy most?<select id="liked"><option value="unknown">No Rating</option><option value="combat">Combat Feel</option><option value="builds">Weapons & Builds</option><option value="art">Characters & Scenery</option><option value="story">Story & Forms</option><option value="rooms">Rooms & Exploration</option></select></label><label>How was the difficulty?<select id="difficulty"><option value="unknown">No Rating</option><option value="easy">Too Easy</option><option value="right">About Right</option><option value="hard">Too Hard</option></select></label><label class="full">What would you keep or change?<textarea id="feedbackText" maxlength="500" placeholder="For example: a larger magatama orbit, or a dimmer light beam…"></textarea></label><button class="primary" id="saveFeedback" type="submit">Save Run and Feedback</button></form><div class="actions"><button class="secondary" id="again">Begin Again</button><button class="ghost" id="exportRun">Export JSON</button><button class="ghost" id="goHome">Return to Shrine</button></div></section></div>`,'wide result-modal');$('#feedbackForm').onsubmit=async e=>{e.preventDefault();G.session.feedback={enjoyment:null,liked:$('#liked').value,difficulty:$('#difficulty').value,comment:$('#feedbackText').value};G.event('feedback_submitted');await G.upload();$('#saveFeedback').disabled=true;$('#saveFeedback').textContent='Saved Locally';$('#feedbackText').disabled=true;$('#liked').disabled=true;$('#difficulty').disabled=true;};$('#again').onclick=()=>G.start();$('#exportRun').onclick=()=>G.download();$('#goHome').onclick=()=>{G.state='home';G.activate('home');G.hideModal();};};
G.updateHud=()=>{if(!G.p||G.state==='home')return;const p=G.p;$('#level').textContent='Lv. '+p.level;$('#hpBar').style.width=G.clamp(p.hp/p.maxHp*100,0,100)+'%';$('#hpText').textContent=Math.ceil(p.hp)+' / '+p.maxHp;$('#shieldText').textContent=p.shield?'Shields ×'+p.shield:'';$('#gold').textContent=p.gold;$('#chapter').textContent=G.regions[Math.min(G.regions.length-1,G.act)].name;$('#roomName').textContent=({battle:'Purification Grounds',elite:'Wild Spirit Trial',forge:'Flint Forge',shrine:'Sanctuary',event:'Chance Encounter',shop:'Lantern Merchant',boss:'Seat of the Wild Spirit'}[G.roomType])||'Journey Ahead';$('#roomClock').textContent=['battle','elite'].includes(G.roomType)?'Seal opens in '+Math.max(0,Math.ceil(G.roomTarget-G.roomTime))+'  s':G.roomType==='boss'?'Defeat the Wild Spirit':'Approach the altar and press E';$('#roomProgress').style.width=Math.min(100,G.roomTime/(G.roomTarget||22)*100)+'%';$('#xpBar').style.width=Math.min(100,p.xp/p.nextXp*100)+'%';$('#bossHud').hidden=!G.boss;if(G.boss){$('#bossName').textContent=G.boss.name;$('#bossBar').style.width=Math.max(0,G.boss.hp/G.boss.maxHp*100)+'%';}
 $('#weaponName').textContent=G.form().name+' +'+p.weaponLevel;$('#dashText').textContent=p.dashCd>0?p.dashCd.toFixed(1)+'s':'Featherstep';$('#skillText').textContent=p.skillCd>0?p.skillCd.toFixed(1)+'s':p.weaponLevel>=3?'Divine Armament Unleashed':'Kusanagi Technique';$('#awakeText').textContent=p.power>=100?'Whitebird Crossing · Ready':Math.floor(p.power)+'%';$('#waterText').textContent=p.waterCd>0?p.waterCd.toFixed(1)+'s':(G.waterArts.find(a=>a.id===p.waterArt)?.name||'Water Wave');$('#blackSkill').hidden=!p.blackUnlocked;$('#blackText').textContent=p.black?'End Bloodrage':'Bloodrage';$('#relicStrip').innerHTML=(p.equipped||[]).map(id=>{const r=G.relics.find(x=>x.id===id);return `<span title="${r.name}: ${r.text}">${G.iconHTML(r.icon,r.iconSet||'items')}</span>`;}).join('');$('#runStamp').textContent='';const inter=G.interactable&&G.state==='running';$('#interactHint').hidden=!inter;if(inter)$('#interactHint').textContent=G.distance(p,G.interactable)<110?'E ·  and '+({forge:'Smith',shrine:'Sanctuary',event:'Traveler',shop:'Merchant'}[G.interactable.type])+'Interact':'Approach the central altar and press E';const img=document.querySelector('.vitals img');const src='assets/'+G.portrait()+'.png';if(img.getAttribute('src')!==src)img.src=src;
};
function records(){G.modal('<div class="eyebrow">Run Journal · Saved Locally</div><h2>Your Journeys</h2><p>Human runs and automated regression runs are labeled separately. Older records remain at the previous version’s address.</p><div id="recordList"></div><button class="secondary" id="closeRecords">Return to Shrine</button>');$('#recordList').textContent=G.records.length?'':'No records yet.';for(const r of G.records.slice(0,16)){const div=document.createElement('div');div.className='record';const span=document.createElement('span');span.textContent=`${r.actor_type==='human'?'Human':'Auto'} · ${r.status} · ${Math.round(r.duration)}  s · ${r.version}`;const b=document.createElement('button');b.textContent='Export';b.onclick=()=>G.download(r);div.append(span,b);$('#recordList').append(div);}$('#closeRecords').onclick=G.hideModal;}
function lore(){G.modal(`<div class="eyebrow">Sources & Adaptation</div><h2>A Life Beyond the Legend</h2><div class="lore-grid"><article><h3>Kusanagi, Flint and the Whitebird</h3><p>Inspired by the escape from fire during the eastern campaign, Ototachibana’s comb and the whitebird after death. Reed burning, shields and Featherstep are combat adaptations.</p></article><article><h3>The Three Regalia and Water Orochi</h3><p>The sword, mirror and magatama become weapons and relics. Water Orochi is an original game technique, not an ability attributed to Yamato Takeru in the Kojiki.</p></article><article><h3>Imperial Command and the Bloodstained Prince</h3><p>The former-self branch draws on the tragic tension between father and son. Keiko is a human emperor. His phantom, the dark transformation, resurrection and renewed life are fictional adaptations.</p></article><article><h3>This Homeward Journey</h3><p>Across five chapters, autonomy contends with command. This game changes the endings at Mount Ibuki and Hashirimizu. The mountain and sea gods’ battles and dialogue are fictional adaptations.</p></article></div><p><a href="https://kojiki.kokugakuin.ac.jp/zh/about-kojiki/outline/" target="_blank" rel="noopener">Kokugakuin University: Kojiki Overview ↗</a></p><button class="primary" id="closeLore">Return to Shrine</button>`);$('#closeLore').onclick=G.hideModal;}
G.showCollection=()=>{
 const paint=()=>{G.modal(`<div class="eyebrow">Shrine Collection · Boss Relics</div><h2>Choose a Relic to Bring</h2><p>Boss relics you claim appear here. Bring up to one when starting a run. Your starting relic is recorded in the run history.</p><button class="secondary" id="noHeirloom">Bring No Relic ${!G.heirloom?'✓':''}</button><div class="cards many">${G.bossRelics.map((r,i)=>{const unlocked=G.collection.includes(r.id);return `<button class="card ${G.heirloom===r.id?'rare':''}" data-heirloom="${i}" ${unlocked?'':'disabled'}>${G.iconHTML(r.icon,r.iconSet||'boss')}<small>${G.bosses[r.boss].name} · ${unlocked?'Collected':'Not Yet Obtained'}</small><h3>${r.name}</h3><p>${r.text}</p><kbd>${G.heirloom===r.id?'Selected':unlocked?'Click to Bring':'Defeat the matching boss and choose this relic'}</kbd></button>`;}).join('')}</div><button id="closeCollection" class="primary">Return to Shrine</button>`,'wide');$('#noHeirloom').onclick=()=>{G.heirloom=null;G.saveCollection();paint();};document.querySelectorAll('[data-heirloom]').forEach(b=>b.onclick=()=>{G.heirloom=G.bossRelics[+b.dataset.heirloom].id;G.saveCollection();paint();});$('#closeCollection').onclick=G.hideModal;};paint();
};
document.querySelector('.home-actions').insertAdjacentHTML('beforeend','<button id="collectionBtn">Boss Relic Collection</button>');$('#collectionBtn').onclick=G.showCollection;
// Keep active skills visible; all icons use generated, locally bundled artwork.
document.querySelector('.skillbar').insertAdjacentHTML('beforeend','<div class="water-skill"><kbd>R</kbd><b id="waterText">Water Wave</b></div><div id="blackSkill" hidden><kbd>T</kbd><b id="blackText">Bloodrage</b></div>');
$('#startBtn').onclick=()=>{unlock();G.start();};$('#characterHome').onclick=G.character;$('#characterBtn').onclick=G.character;$('#mapBtn').onclick=G.showMap;$('#pauseBtn').onclick=()=>G.pause();$('#recordsBtn').onclick=records;$('#loreBtn').onclick=lore;$('#soundBtn').onclick=()=>{G.sound=!G.sound;$('#soundBtn').textContent='Sound: '+(G.sound?'On':'Off');if(G.sound)unlock();};
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;if(G.state==='choice'){let n=Number(e.key);if(n>=1&&n<=9)G.choose(n-1);return;}if(G.state==='boss_intro'){if(e.code==='Enter')$('#bossStart').click();return;}if(e.code==='Escape'){if(G.state==='running')G.pause();else if(G.state==='paused')G.resume();else if(G.state==='character')$('#closeCharacter')?.click();else if(G.state==='map')$('#backMap')?.click();else if(G.state==='home')G.hideModal();return;}if(e.code==='KeyC'&&['running','home'].includes(G.state)){G.character();return;}if(e.code==='KeyM'&&G.state==='running'){G.showMap();return;}if(G.state!=='running')return;G.keys.add(e.code);G.event('input',{code:e.code,pressed:true});if(e.code==='Space')G.dash();if(e.code==='KeyF')G.skill();if(e.code==='KeyR')G.waterSkill();if(e.code==='KeyQ')G.awaken();if(e.code==='KeyT')G.blackMode();if(e.code==='KeyE')G.interact();});
window.addEventListener('keyup',e=>{if(G.keys.delete(e.code)&&G.state==='running')G.event('input',{code:e.code,pressed:false});});window.addEventListener('blur',()=>{G.keys.clear();if(G.state==='running'&&G.session?.actor_type==='human')G.pause('focus_lost');});document.addEventListener('visibilitychange',()=>{if(document.hidden){G.keys.clear();if(G.state==='running'&&G.session?.actor_type==='human')G.pause('tab_hidden');}});window.addEventListener('resize',G.resize);window.addEventListener('pagehide',()=>{if(G.session&&!G.ended)G.persist(true);});
G.uiReady=true;G.initializeBridge();})();
