'use strict';
(() => {
const G=WB,$=G.$;
G.uiStory=(act,then)=>{
 const r=G.regions[act],words=[['Protect the Villagers','Tonight, I’ll save the people who are still alive.'],['I Choose Where I Go','You gave me a name. You cannot live my life for me.'],['Help Those on the Mountain','I’ve come to bring you down safely.'],['Cross the Sea Together','Everyone deserves a boat home.'],['Change the Journey with This Sword','The old tale can remember my death. I’ll live to see another dawn.']][act];
 G.offer(r.name,r.intro,[{id:'self',name:words[0],icon:2,text:'Protect those beside you. Max HP +8. Restore 12 HP.',effect:{autonomy:1,maxHp:8,heal:12},tags:['narrative','autonomy','survival']},{id:'command',name:'Borrow the Old Command',icon:0,text:'A familiar voice guides the sword. Damage +10%. Lose a little HP.',effect:{obedience:1,damage:.1,hp:-5},tags:['narrative','obedience','risk']}],c=>{
  if(c.id==='self'){G.autonomy++;G.p.maxHp+=8;G.p.hp=Math.min(G.p.maxHp,G.p.hp+12);G.toast(words[1]);}else{G.obedience++;G.p.damage+=.1;G.p.hp=Math.max(1,G.p.hp-5);}
  const was=G.p.blackUnlocked;G.p.blackUnlocked=G.obedience>=2||G.has('blood_wrap');if(!was&&G.p.blackUnlocked)G.toast('An old command echoes in the blade · T Bloodrage');
  G.event('narrative_choice',{act,choice:c.id,autonomy:G.autonomy,obedience:G.obedience});
  if(act===G.regions.length-1&&G.p.blackUnlocked)G.offer('Who Looks Back from the Sea?','He holds the same sword as you. He says that following orders makes it easier to forget.',[{id:'prince',name:'Reach for the Reflection',icon:0,text:'Face the Bloodstained Prince and hear the story he could not tell.',effect:{shadow_final:true},tags:['hidden_boss','selfhood']},{id:'magatsu',name:'Protect the Living',icon:6,text:'Magatsu still calls from the tide. Help the people on the shore get home first.',effect:{shadow_final:false},tags:['main_boss','protection']}],v=>{G.shadowFinal=v.id==='prince';then();},'final_path');else then();
 },'narrative');
 $('#modal').classList.add('story-modal');$('#modal').insertAdjacentHTML('afterbegin',`<img class="story-art" src="assets/${['hero_long','father_portrait','aragami_portrait','sea_portrait','hero_divine_v2'][act]}.png" alt="Chapter artwork"><span class="chapter-numeral">${['I','II','III','IV','V'][act]}</span>`);
};
G.character=()=>{
 if(!['home','running','paused'].includes(G.state))return;const previous=G.state;G.state=previous==='home'?'home':'character';G.event('character_opened');let tab='stats';
 const close=()=>{G.hideModal();if(previous==='paused')G.pause();else G.state=previous;};
 function paint(){
  const p=G.p&&!G.ended?G.p:null;
  G.modal(`<div class="character-shell"><aside class="character-art"><img src="assets/${p?G.portrait():'hero_long'}.png" alt="Current character form"><div><small>Whitebird Soul</small><h2>Ousu-no-Mikoto</h2><p>${p?.black?'Bloodrage · Echo of the Emperor':p?.weaponLevel>=3?'Divine · Heaven’s Light':'Ousu · A Journey of His Own'}</p></div></aside><section class="character-content"><div class="character-top"><div class="eyebrow">Character Journal</div><button id="closeCharacter" class="ghost">Close ×</button></div><nav class="tabs">${[['stats','Stats'],['gear','Weapons'],['skills','Active Techniques'],['talents','Passives'],['relics','Relic Bag'],['library','Build Codex']].map(([id,name])=>`<button data-tab="${id}" class="${id===tab?'active':''}">${name}</button>`).join('')}</nav><div id="tabBody"></div></section></div>`,'character-modal wide');
  $('#closeCharacter').onclick=close;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;paint();});let html='';
  const talentCards=category=>G.talents.filter(t=>t.category===category&&(!t.weapon||!p||t.weapon===p.weapon)).map(t=>`<article class="${p&&G.lv(t.id)?'learned':''}">${G.iconHTML(t.icon,t.iconSet||'items')}<div><b>${t.name} <small>${p?G.lv(t.id):0} / ${t.max}</small></b><p>${t.text}</p></div></article>`).join('');
  if(tab==='stats')html=`<h2>${p?'Your Current Form':'Ousu-no-Mikoto'}</h2><p>${p?G.recipe(p.weapon,p.rune||'echo'):'Choose the powers to carry on this journey. The sword remembers the past. You choose where to go.'}</p><div class="stat-grid">${(p?[['HP',`${Math.ceil(p.hp)} / ${p.maxHp}`],['Damage Multiplier',G.power().toFixed(2)+'×'],['Move Speed',p.speed],['Armor Reduction',p.armor+G.lv('ward')],['Shield',p.shield],['Coins',p.gold],['Relic Slots',p.equipped.length+' / 4'],['Autonomy',G.autonomy]]:[['Weapons',12],['Core Inscription',20],['Blade Inscription',240],['Journey Chapter',5]]).map(([name,value])=>`<div><small>${name}</small><strong>${value}</strong></div>`).join('')}</div><p class="note">${p?.blackUnlocked?'Bloodrage echoes in the sword. Press T in combat to toggle it.':'The whitebird’s journey is not yet finished.'}</p>`;
  if(tab==='gear'){const w=p?G.form():G.weapons[0];html=`<h2>${w.name}</h2><div class="equipment-main">${G.iconHTML(w.icon,'weapons')}<div><h3>${p?'Tempering '+p.weaponLevel+'  Rank':'Journey Not Started'}</h3><p>${w.text}</p></div></div><h3>Power in the Blade</h3><p>${p?.weaponLevel>=3?'Murakumo is awake. F releases piercing heavenly light.':p?.weaponLevel>=1?'The sword carries flint sparks and can ignite nearby grass.':'Your sword art changes with your weapon.'}</p><h3>Armor</h3><p>${p?'Mending '+p.armorLevel+'  rank · Base damage reduction '+p.armor:'Bronze Armor and Old White Robes'}</p><p class="note">The forge changes how your sword responds. Give it to the smith to see the upgrade.</p>`;}
  if(tab==='skills'){
   const arts=G.waterArts.filter(a=>!p?a.level===0:G.lv('water')>=a.level);
   html=`<h2>Active Techniques</h2><div class="item-list"><article>${G.iconHTML(0)}<div><b>F · Weapon Technique</b><p>Use your current weapon’s unique sword art.</p></div></article><article>${G.iconHTML(2)}<div><b>Space · Featherstep / Q · Whitebird Crossing</b><p>Dash through enemies. Awakening clears projectiles and strikes groups of foes.</p></div></article></div><h3>R · Equipped Water Art</h3><div class="water-list">${arts.map(a=>`<button data-water="${a.id}" ${p?'':'disabled'} class="${p?.waterArt===a.id?'selected':''}">${G.iconHTML(a.icon)}<b>${a.name}</b><p>${a.text}</p><small>${p?.waterArt===a.id?'Selected':'Equip'} · ${a.cd}  s</small></button>`).join('')}</div><h3>Technique Upgrades</h3><div class="talent-grid">${talentCards('active')}</div>`;
  }
  if(tab==='talents')html=`<h2>Passives</h2><p>Passives work automatically. No cast is needed.</p><div class="talent-grid">${talentCards('passive')}</div>`;
  if(tab==='relics')html=`<h2>Bag & Relic Slots</h2><p>Equip up to four relics. Unequipped relics remain in your bag and can be swapped here. The forge can infuse them.</p><div class="relic-slots">${[0,1,2,3].map(i=>{const r=G.relics.find(r=>r.id===p?.equipped[i]);return `<span>${r?G.iconHTML(r.icon,r.iconSet||'items')+'<b>'+r.name+'</b>':'<b>Empty Relic Slot</b>'}</span>`;}).join('')}</div><div class="cards many relic-bag">${(p?p.relics:[]).map(id=>{const r=G.relics.find(r=>r.id===id);return `<button data-relic="${id}" class="card ${G.has(id)?'rare':''}">${G.iconHTML(r.icon,r.iconSet||'items')}<small>${p.relicRanks[id]||1}  rank · ${G.has(id)?'Equipped':'Bag'}</small><h3>${r.name}</h3><p>${G.relicText(r)}</p><kbd>${G.has(id)?'Unequip':'Equip'}</kbd></button>`;}).join('')||'<p>Defeat wild spirits, open chests or visit the Lantern Merchant to find relics.</p>'}</div>`;
  if(tab==='library')html=`<h2>Weapons & Inscriptions</h2><p>Choose a weapon to preview how different inscriptions work with it.</p><label>Weapon <select id="libraryWeapon">${G.weapons.map(w=>`<option value="${w.id}">${w.name}</option>`).join('')}</select></label><div id="combinationGrid" class="combination-grid"></div>`;
  $('#tabBody').innerHTML=html;
  document.querySelectorAll('[data-water]').forEach(b=>b.onclick=()=>{p.waterArt=b.dataset.water;G.event('water_art_equipped',{id:p.waterArt,reason:'player_choice'});paint();});
  document.querySelectorAll('[data-relic]').forEach(b=>b.onclick=()=>{G.equipRelic(b.dataset.relic);paint();});
  if(tab==='library'){const fill=()=>$('#combinationGrid').innerHTML=G.runes.map(r=>`<article>${G.iconHTML(r.icon,'runes')}<div><b>${r.name}</b><p>${G.recipe($('#libraryWeapon').value,r.id)}</p></div></article>`).join('');fill();$('#libraryWeapon').onchange=fill;}
 }paint();
};
$('#characterHome').onclick=G.character;$('#characterBtn').onclick=G.character;
const hud=G.updateHud;G.updateHud=()=>{hud();if(G.p&&G.state!=='home'){$('#weaponName').textContent=G.form().name;$('#roomName').textContent=G.roomType==='shop'?'Lantern Merchant':$('#roomName').textContent;}};
const observe=G.bridgeTarget.observe;G.bridgeTarget.observe=()=>{const o=observe();if(o.player){Object.assign(o.player,{equipped_relics:[...G.p.equipped],relic_ranks:{...G.p.relicRanks},water_cooldown:G.p.waterCd});}return o;};
})();
