import {HUNTS} from './hunts.js';
import {huntAvailability,HUNT_REWARDS} from './hunt-progress.js';
import {ACTION_NAMES} from './fishing-actions.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const silhouettes={ironjaw:'M24 64 8 41 13 75 9 99 35 79Q59 102 101 79L117 69 112 52 100 45 86 44 76 30 66 43 52 34 44 50Z',stormeel:'M111 43Q74 7 49 34T63 70Q92 82 73 95 49 111 19 79L10 76Q34 120 77 113 119 105 95 78L70 56Q48 37 73 35L91 50 99 46 105 52Z M85 30 82 16 99 29 107 16 110 35Z',ancientshark:'M15 68Q48 38 68 44L77 17 91 43Q113 48 121 67L101 80 75 79 65 99 57 78 33 78 7 105 14 73 5 44Z'};
function creatureMark(id){return `<svg class="hunt-creature-mark" viewBox="0 0 132 132" aria-hidden="true"><path d="${silhouettes[id]||silhouettes.ironjaw}" fill="currentColor"/><path d="M91 55h3M77 53l-3 15M69 53l-3 17" fill="none" stroke="#153d39" stroke-width="3" stroke-linecap="round"/></svg>`;}
export const HUNT_COPY={
  ironjaw:{title:'礁背铁颚',region:'落帆浅礁',biome:'reef',image:'reef.png',tag:'01 · 礁甲与冲撞',brief:'旧网道被一尾铁甲巨石斑占了。周叔借来结实的缆绳，阿禾已经留好了砂锅。',mechanic:'避开红色冲撞线，等它撞礁露出金色弱点。蓄力命中后，在收线窗口按 R。',reward:'首猎：100 贝币 · 3 份礁王鲜切',note:'周叔把新缆绳的结打了又打：“别硬扛，等它自己露出破绽。今晚那锅汤，我们一起喝。”'},
  stormeel:{title:'雷冠长鳗',region:'回声雷涌',biome:'cave',image:'cave.png',tag:'02 · 雷流与安全区',brief:'暴潮把一条电鳗带进了旧盐场。小夏在海图上描下雷流的间隙，等你带回今晚的新菜。',mechanic:'看清电流预警，穿过安全空隙。电能放尽时攻击发亮部位，半血后留意第二道波。',reward:'首猎：140 贝币 · 4 份雷鳗腹肉',note:'小夏在餐牌上画了一道弯弯的雷：“菜名别太吓人，苏婆婆看见会说我们连天气都下锅了。”'},
  ancientshark:{title:'吞舟古鲨',region:'沉灯外海',biome:'abyss',image:'abyss.png',tag:'03 · 吸流与怒潮',brief:'深水航道传来沉重的水声。云姨递来旧航海灯，让你沿着光回家；小馆为这场远航多留了一张桌。',mechanic:'吸流前向外游，闪避扇形吐浪；露出咽喉时蓄力射击。半血进入怒潮，别贪收线。',reward:'首猎：200 贝币 · 5 份深潮厚切',note:'阿禾没有问你追了多远，只把热茶推过来：“回来就好。今天慢慢切，大家都等得起。”'}
};
export function huntBoardMarkup(progress) {
  return `<section class="hunt-board"><header class="hunt-header"><div class="hunt-heading"><span class="eyebrow">蓝湾航海局 · 外海手绘图</span><h1>潮外狩猎</h1><p>循着潮线出海，带一桌好菜回家。</p></div><div class="hunt-actions"><button class="primary" id="hunt-practice">先练习捕鱼动作</button><button id="hunt-board-back">回到小馆</button></div></header><div class="hunt-chart"><div class="hunt-chart-north" aria-hidden="true"><span>北</span><i></i><small>BLUE BAY</small></div><span class="hunt-chart-label" aria-hidden="true">蓝湾小馆<br><small>晚饭在等你</small></span><svg class="hunt-chart-route" viewBox="0 0 1200 500" preserveAspectRatio="none" aria-hidden="true"><path d="M40 420Q130 420 192 278T532 145 910 208 1140 90"/><path d="M35 425l15-28 17 21-17 17z" class="hunt-map-boat"/></svg><div class="hunt-grid">${HUNTS.map((def,i)=>{const c=HUNT_COPY[def.id],a=huntAvailability(progress,def.id),r=HUNT_REWARDS[def.id];return `<article class="hunt-card hunt-route-${i+1} ${a.available?'':'is-locked'} ${a.cleared?'is-cleared':''}"><div class="hunt-card-art" style="--hunt-region-art:url('./assets/art/${c.image}')"><span class="hunt-coordinate">${['N 12° · E 07°','N 24° · E 18°','N 39° · E 32°'][i]}</span><div class="hunt-medallion">${creatureMark(def.id)}<span class="hunt-map-number">0${i+1}</span>${a.cleared?'<span class="hunt-map-stamp">已首猎</span>':''}</div><small>${c.region}</small><strong>${c.title}</strong><span class="hunt-route-tag">${c.tag}</span></div><div class="hunt-card-body"><p class="hunt-mechanic">${c.mechanic}</p><div class="hunt-reward">${r.firstCredits} 贝币 <span>＋</span> ${r.firstPortions} 份${r.ingredient}</div><button class="primary" data-hunt="${def.id}" ${a.available?'':'disabled'}>${a.available?(a.cleared?'再次出航':'接下狩猎委托'):'完成上一场狩猎后解锁'}</button><small>${a.cleared?'已首猎 · 每日首场复战有少量补给，其余可自由练习':a.available?'专用气瓶与鱼叉已备好，随时可以回来。':esc(a.reason||'先熟悉上一片海的水流。')}</small></div></article>`;}).join('')}</div></div><footer class="hunt-footer"><span>船长手记 <b>三场独立狩猎 · 首猎依次解锁</b></span><p><kbd>WASD</kbd> 游动 <kbd>空格</kbd> 蓄力 / 发射 <kbd>Shift</kbd> 闪避 <kbd>R</kbd> 收线 <kbd>Esc</kbd> 暂停</p></footer></section>`;
}
export function huntHudMarkup(h) {
  const c=HUNT_COPY[h.id] || HUNT_COPY[h.boss?.id] || HUNT_COPY.ironjaw;
  return `<section class="hunt-hud"><div class="hunt-top"><div class="hunt-boss-panel"><span class="eyebrow">${c.region} · 潮外狩猎</span><h2>${c.title}<small id="hunt-phase">阶段 1</small></h2><div class="hunt-boss-health"><i id="hunt-boss-fill"></i></div><span id="hunt-boss-numbers"></span></div><div class="hunt-status"><b>汐 · 狩猎潜水表</b><div class="hunt-gauge-face"><span class="hunt-gauge-symbol" aria-hidden="true">汐</span><span id="hunt-player-numbers"></span><div class="hunt-player-health"><i id="hunt-health-fill"></i></div></div><span id="hunt-oxygen"></span><button id="hunt-pause" class="hunt-action">暂停 · Esc</button></div></div><div class="hunt-warning" id="hunt-warning" role="status"></div><div class="hunt-bottom"><div class="hunt-tips"><div class="hunt-tip-heading"><b id="hunt-action-name">游动</b><span id="hunt-window">等待破绽</span></div><p id="hunt-hint">${c.mechanic}</p><div class="hunt-charge"><i id="hunt-charge-fill"></i></div><small id="hunt-charge-label">空格：按住蓄力，松开发射</small></div><div class="hunt-controls" aria-label="狩猎动作"><button id="hunt-dodge" class="hunt-action">闪避 · Shift</button><button id="hunt-fire" class="hunt-action primary">蓄力鱼叉</button><button id="hunt-reel" class="hunt-action">收线 · R</button></div></div></section>`;
}
export function updateHuntHud(root,h,latched=false) {
  const set=(id,text)=>{const el=root.querySelector('#'+id);if(el)el.textContent=text;};
  const fill=(id,n)=>{const el=root.querySelector('#'+id);if(el)el.style.width=Math.max(0,Math.min(100,n))+'%';};
  const b=h.boss,p=h.player;
  fill('hunt-boss-fill',b.hp/b.maxHp*100);fill('hunt-health-fill',p.health);fill('hunt-charge-fill',(p.charge||0)*100);
  set('hunt-boss-numbers',`${Math.ceil(b.hp)} / ${b.maxHp}`);set('hunt-phase',`阶段 ${b.phase||1}`);
  set('hunt-player-numbers',`生命 ${Math.ceil(p.health)} / 100`);set('hunt-oxygen',`氧气 ${Math.ceil(p.oxygen)} · 闪避 ${p.dodgeCooldown>0?p.dodgeCooldown.toFixed(1)+'秒':'就绪'}`);
  set('hunt-action-name',ACTION_NAMES[p.action]||'游动');set('hunt-window',h.tether?'鱼叉已挂住 · R 收线':b.weak?'弱点暴露 · 蓄力反击':'观察预警 · 保持距离');
  set('hunt-warning',h.message||'');set('hunt-fire',latched?'发射鱼叉':'蓄力鱼叉');
  set('hunt-charge-label',(p.charge||0)>.1?`蓄力 ${Math.round(p.charge*100)}% · 松开空格或点击发射`:'空格：按住蓄力，松开发射');
}
